### ISSUE TITLE
Add commit empty body rejection to CI 

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1206]
Given we are asking to comply to https://chris.beams.io/posts/git-commit/ for commits, we should start rejecting emtpy commit bodies or bodies  that contain only the signature.

**Comment by tylerauerbeck** [comment]
I think this is a good idea to put in place, but using the current `commitlint` implementation this is realistically probably blocked by https://github.com/conventional-changelog/commitlint/issues/3411. Due to the various ways that folks may (or may not) sign their commits, `commitlint` can assume that the `Signed-off-by` line is a body, which isn't what we would want and can result in unexpected outcomes.
