### ISSUE TITLE
configure local networking with kind cluster and mettallb

### ISSUE THREAD

**Issue by WinterSoilder** [metallb/metallb#1244]
I wanted to know how can other machines on the same network(wifi router) can access the given loadbalancer ip address from metallb
specifically i have configured my metallb on kind clusters which use docker networking, so how to i expose it to anyone connected to my private network?

**Comment by fedepaol** [comment]
I am afraid you can't.
In BGP mode, metallb will advertise your "nodes" as next hops, and the router won't be aware of that unless you put dnat routes on your host.
In L2 mode, the arp requests won't make it to the "node" as they'll stop at your host level.

**Comment by WinterSoilder** [comment]
@fedepaol Ok thanks for the info. correct me if i am wrong... doesnt this beat the purpose of having a baremetal loadbalancer? Or are u implying this limitation is if i am using kind cluster? if its a problem with kind what alternative can u suggest?

**Comment by fedepaol** [comment]
It is a limitation of using a kind cluster, and eventually running a cluster inside a host.
The baremetal loadbalancer (and I'd say kubernetes in general) is meant for cluster where nodes are exposed on the network, or you circumvent it with doing additional plumbing on your host so that the kind (or minikube, or whatever) cluster behaves as if it was.
