### ISSUE TITLE
Undocumented removal of config flag for speaker/controller

### ISSUE THREAD

**Issue by duhruh** [metallb/metallb#1283]
It appears since https://github.com/metallb/metallb/commit/d58b0112df3174fd309bd1a850a90cdf2302adfb#diff-76095ee6d05db635f9e683b8573f1cefe9827338f87471a66afd29a8e9efe256L126 that the installation process documented at https://metallb.universe.tf/installation/ for metallb is now broken. It looks like this PR removed the config flag, and since it's still referenced in the provided metallb.yaml we get a flag provided but not defined error. I checked the release notes page https://metallb.universe.tf/release-notes/ and it also does not mention the removal of this flag. 

I believe this also holds true for the speaker and the controller.

**Comment by fedepaol** [comment]
@duhruh the config flag was remove on the main branch, which happens to be the development branch. The docs will align when a formal release is finalized, and we will provide a way to migrate from the existing configmap to the new crds.

Also, you mention metallb.yaml, but https://github.com/metallb/metallb/blob/v0.12.1/manifests/metallb.yaml contains it (because that version still handles the config), whereas https://github.com/metallb/metallb/blob/main/manifests/metallb.yaml doesn't.

I suggest to pin to a released version until the next one is released. If I am missing something, or we left broken manifests somewhere, please let us know because that must be fixed.

**Comment by dimm0** [comment]
The manifest for frr mode uses the main tag, which crashloops for this reason. It still has the config option.

**Comment by fedepaol** [comment]
@dimm0 we have https://github.com/metallb/metallb/issues/1265 to track that
