### ISSUE TITLE
X-Forwarded-For IP, equivalent, when using kube-proxy?

### ISSUE THREAD

**Issue by BloodyIron** [metallb/metallb#1309]
Hey so nginx and other httpd's have the ability to forward the source IP when proxying connections (reverse-proxy, or otherwise). And I believe in some configurations MetalLB strips the source IP and replaces it with the kube-proxy IP (or something along those lines, I'm still learning).

Any chance we can get some sort of equivalent going on for X-Forwarded-For to pass along original source IPs? Without source IPs banlists are useless for toolsa that have them.

**Comment by fedepaol** [comment]
@BloodyIron that's not metallb.
It's the SDN of your choice, when you use external traffic policy = cluster and the traffic gets redirected to another node, there's nothing metallb can do in that regard. MetalLB "only" makes it possible for the traffic to reach the node, all the rest is done by the primary CNI.

**Comment by BloodyIron** [comment]
Okay well the reason I thought that it was a MetalLB aspect was because the MetalLB documentation said this is the behaviour. Perhaps that aspect of the documentation should be adjusted to be more accurate and clear.

So, if I am using Calico, is it possible to do x-forwarded-for, for IP addresses, in "traffic policy = cluster" mode?

**Comment by fedepaol** [comment]
Yep, metallb describes the behaviour implemented by kube-proxy (I think), and it's not wrong about that.
The thing is, metallb's responsability is to drive the traffic to the node, the last mile of the path is handled by the cni of your choice, including the snat when the destination pod is on another node. I am not a calico expert (actually, I am expert of nothing :P ), but I'd try to ask them the very same question because metallb has no control on the behaviour.

**Comment by jynw** [comment]
hi all,
is it possible to do x-forwarded-for, for IP addresses, in "traffic policy = local" mode? any document about this?
