### ISSUE TITLE
Is it intended to always retry in servicereload_controller.go?

### ISSUE THREAD

**Issue by ckyoog** [metallb/metallb#1311]
Hello,

I've been reading the code. Looks like a new controller framework and a bunch of new CRDs were added in lately. I am so excited, I can't wait for a new release. And also, some code confused me, like the following.

It doesn't look right, since the `retry` is always `true`. It will always retry even though the callback `Handler` returns <code>SyncStateError**NoRetry**</code>. If always `retry` is intended, then the `if retry` seems to be unnecessary.

This is more like a question probably than an issue. There is no **github discussion** in this repo, I otherwise wouldn't post it here.

https://github.com/metallb/metallb/blob/35e41dea662b43e91b5c2a7338b92d27eb059a4d/internal/k8s/controllers/servicereload_controller.go#L81-L103

**Comment by fedepaol** [comment]
Good catch, thanks a lot! I'll file a PR for that.
If you have other parts of the codebase that do not look clear, please let us know. We already had a discussion about the controller glue not being covered by tests (and the fact that e2e is not enough in this case, because it may work but also do unnecessary loops as in this case), and we'll cover this part too.
