### ISSUE TITLE
Use ginkgo instead of go test in CI

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1320]
Ginkgo fails if some focused test is left in the codebase (FIt, FEntry, etc), avoiding the risk of committing code with focused tests in code that may let us think the CI is good while it's running a subset of tests.

**Comment by nvzard** [comment]
Hey @fedepaol, I am new here and would like to contribute. Can you please assign this to me?

**Comment by nvzard** [comment]
Hey @fedepaol ,

I just wanted to clarify that the changes for this PR will involve:

- Replacing all the existing tests which are using `func TestX(t *testing.T) {}` with the Ginkgo and Gomega DSLs.
- Changes in tasks.py to use `ginkgo` and `ginkgo -race` CLI to invoke the tests in CI instead of `go test` and `go test -race`.

Please, correct me if I am wrong or missing something.

**Comment by fedepaol** [comment]
The scope of this is only the latter.
It's totally fine (and I like) having plain go test for unit tests and ginkgo tests for e2e. The issue is, when we run ginkgo via go test it doesn't fail if we forget a focused entry, while ginkgo does. That's why I'd like to replace the execution from tasks (which, in turn, is executed in our CI)

**Comment by nvzard** [comment]
That makes sense, thanks for clarifying!

**Comment by fedepaol** [comment]
Closed by https://github.com/metallb/metallb/pull/1670
