### ISSUE TITLE
Allow preferences for node announcement

### ISSUE THREAD

**Issue by BhasherBEL** [metallb/metallb#1335]
I'm running MetalLB on a small k3s cluster with one master and two workers. I'm trying to make some critics {critical?} HA pods. They are running on every node for redundancy and use a load-balancing service to send traffic to the pods.

My problem is that announcement is always done by the master, which that makes the service not HA.
If a worker become unavailable, everything continues to works well as the two others nodes continues to handle the traffic.
However, should the master become unavailable, the cluster falls in a "legacy mode". As the master decides who makes announcements and is unreachable, the workers will not handle any traffic.

One solution I found for that case would be to be able to select which node will preferably make the announcement. In that scenario, if the master fail, the preferred node will continue to manage the traffic.

**Comment by fedepaol** [comment]
Hi @BhasherBEL , among other things (such as being able to configure metallb via CRDs), we will ship a node selector for announcements. You can check the feature here https://github.com/metallb/metallb/blob/main/design/pool-configuration.md , and probably the main repository is starting to be stable enough to be usable.

**Comment by BhasherBEL** [comment]
Thank you a lot for your answer !

Is there any plan to implement NodeAffinity for L2Advertisement/BGPAdvertisement in addition of NodeSelector ?

**Comment by fedepaol** [comment]
Not really. What would be the use case?

**Comment by BhasherBEL** [comment]
Back to my small cluster with one master and three workers, I would set a `NodeAffinity` on the workers (to be able to continue working if the master fail) and if any of the workers are available, the master do the announcement. With `NodeSelector`, if no workers are available, the announcement will just not be done.

**Comment by fedepaol** [comment]
so if I got it right, the current configuration flexibility is not good enough as the join is done on the ipaddresspool, and it would require you to define a single-ip pool per service (in order to have a different node selector), while you still want to have the ips coming from a shared pool.

Side question is, by doing this, you are giving up on having failover if one of those nodes fail. Is that correct?

Need to think about this a bit, the idea of having a service / ns selector on the advertisements is something has been in the back of my head for a while. In general, I prefer having the behaviour driven by the CRDs rather than annotations, because it moves the configuration responsability away from the application to the cluster administrator.
