### ISSUE TITLE
Remove the "experimental" from FRR mode

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1532]
MetalLB with FRR support was released with v0.12.0, adding this issue to track the removal of the experimental warning.
To add more information, the Openshift version of metallb is using FRR by default and was GA-ed around the same time.

**Comment by fedepaol** [comment]
Just to add more color to the "experimental" notice, that was always meant to be "less battle tested" than the native BGP implementation.
We have running CI covering both native and FRR mode, and we have all the interest in fixing bugs related to the FRR mode as soon or later it is going to be the only BGP mode (as per https://github.com/metallb/metallb/blob/main/design/0001-frr.md )

I understand that the wording might scare some users away, so maybe it's now time to remove it, adding a note of being less mature only.

**Comment by emaante** [comment]
Hello,
we've been using MetalLB in production over here at Deutsche Telekom TDI for awhile. Having BFD support (provided by FRR mode) would be nice, but due to telco requirements, "experimental" naming does not fly very well with customers, even if tested (upstream and locally).
Thanks for clarifications @fedepaol , removing this would be very helpful.
