### ISSUE TITLE
cert-manager support

### ISSUE THREAD

**Issue by kfox1111** [metallb/metallb#1642]
Managing certificates/ca's for webhooks is painful. Each project seems to want to do things their own way, and causes cluster-admins to have to learn many different ways of setting the webhooks up, debug them when they fail, try and manage the permissions of each service, etc.

cert-manager has a standardized way of setting all of the webhook stuff up and injecting it into the webhook config. It would be very nice for cluster-admins to be able to use cert-manager to manage the webhooks in metallb instead of metallb doing so.

**Comment by fedepaol** [comment]
We kind of discussed this in the beginning, but having an extra dependency in order to be able to deploy MetalLB felt less than optimal. 

Are you having specific problems with the way metallb handles the certificate, or is this just a general question? If you have an issue, please file it (as you did with the permissions).

I have the feeling that even with CertManager, users that have network issues and all those esoteric issues described in this [very nice post](https://hackmd.io/@maelvls/debug-cert-manager-webhook) would persist, and I'd avoid having yet another knob to deploy metallb.

**Comment by kfox1111** [comment]
metallb rarely exists by itself on the cluster. its simpler for metallb to manage it, itself, in isolation, but its more complicated in the cluster, as a whole to deal with every webhook doing its own thing. Take that document and add the complexity of metallb's implementation, gatekeepers implementation, webhooks for some of the csi drivers, prometheus-operators webhooks, etc etc etc. This decision makes managing certs worse for a lot of clusters IMO. And way more, security sensitive code running in the cluster that could have issues.
