### ISSUE TITLE
Tutorial on kubeadm-dind-cluster instead of Minikube fails

### ISSUE THREAD

**Issue by Hopobcn** [metallb/metallb#171]
**Is this a bug report or a feature request?**:
Bug

**What happened**:
Attempted to follow the tutorial, but using [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster).
But after deploying `test-bgp-router.yaml` the pod ` test-bgp-router-d465f9b7c-6fwwj` failed.

Logs from test-bgp-router in test-bgp-router-d465f9b7c-6fwwj:
```
2018-02-26T22:11:14.123767101Z time="2018-02-26T22:11:14Z" level=info msg="Add a peer configuration for:10.192.0.3" Topic=Peer
2018-02-26T22:11:14.131992974Z 2018/02/26 22:11:14 ZEBRA: Zebra 1.2.2 starting: vty@2601
2018-02-26T22:11:14.136998576Z 2018/02/26 22:11:14 ZEBRA: client 17 says hello and bids fair to announce only bgp routes
2018-02-26T22:11:14.137021709Z 2018/02/26 22:11:14 ZEBRA: Try to set TE Link Param
2018-02-26T22:11:14.137027754Z 2018/02/26 22:11:14 ZEBRA: Try to set TE Link Param
2018-02-26T22:11:14.176935558Z 2018/02/26 22:11:14 ZEBRA: Try to set TE Link Param
2018-02-26T22:11:14.209747823Z 2018/02/26 22:11:14 ZEBRA: Try to set TE Link Param
2018-02-26T22:11:14.25714784Z F0226 22:11:14.256771       1 main.go:78] tcpdump exited with an error: exit status 1
```
Seems to be failing here: https://github.com/google/metallb/blob/master/test-bgp-router/main.go#L78

Events (from dashboard):
```
Back-off restarting failed container
kubelet kube-node-1
spec.containers{test-bgp-router}
48
2018-02-26T22:11 UTC
2018-02-26T22:21 UTC
```
```
Error syncing pod
kubelet kube-node-1
-
6
2018-02-26T22:11 UTC
2018-02-26T22:12 UTC
```

**What you expected to happen**:
Tutorial run through to completion.

**How to reproduce it (as minimally and precisely as possible)**:
```
wget https://cdn.rawgit.com/Mirantis/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.8.sh
chmod +x dind-cluster-v1.8.sh
./dind-cluster-v1.8.sh up
export PATH="$HOME/.kubeadm-dind-cluster:$PATH"
kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.3.1/manifests/test-bgp-router.yaml
[ pod will fail here ]
```

**Anything else we need to know?**:

**Environment**:
- MetalLB version: v0.3.1
- Kubernetes version: v1.8 
- BGP router type/version: N/A
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): 4.13.0-36-generic

**Comment by danderson** [comment]
Arguably this is more a feature request, because nothing says that kubeadm-dind-cluster is supported ;)

Specifically, the test-bgp-router is failing because it assumes that it can do root-level stuff inside the container. It can do that in minikube because it's a VM, but dind probably restricts capabilities more.

I'll try to make things work gracefully, but I won't get to it for several days. If you want to test-drive MetalLB sooner, I suggest just using Minikube (or sending me a PR to fix this! The tcpdump execution is a debugging aid in test-bgp-router, it would be okay to make it fail gracefully ("oh, I can't tcpdump, okay, whatever")

**Comment by Hopobcn** [comment]
> Arguably this is more a feature request, because nothing says that kubeadm-dind-cluster is supported ;)

Yep, I agree. I just wanted to contribute. I didn't now if you ever tried with kubeadm-dind and since its not explicitly stated as not supported I thought I could give it a try :-D

I'll stick with Minikube for now. Thanks!

**Comment by danderson** [comment]
And thank you for contributing! I'd never heard of kubeadm-dind-cluster, so obviously I never tested with it :).

I'll throw it on the pile of things to fix. A PR is very welcome if you have the time/skill to fix this, otherwise it'll go into the backlog.

**Comment by lukaszo** [comment]
@Hopobcn k-d-c(kubeadm-dind-cluster) contributor here. I've just finished tutorial using k-d-c using k8s 1.9 version and everything works just fine. Not sure if we fixed something or if something was fixed in metallb.

@danderson the k-d-c is docker in docker kubernetes cluster. It's biggest advantage over minikube is possibility to have a multi-node cluster.

**Comment by russellb** [comment]
this issue is now a couple years old, and the last comment was that a successful test occurred, so i'm just going to close this one out.
