### ISSUE TITLE
controller: leaving `service.status.loadBalancer.ingress[].hostname` intact

### ISSUE THREAD

**Issue by m-yosefpor** [metallb/metallb#1733]
We have a working setup with metallb+k8s_external coredns plugin for service type loadbalancer discovery and now we can resolve svc-lb hostnames. However I need to be able to set this hostname on service.Status so that it is shown when listing services:

```
$ oc get svc
example-svc      LoadBalancer   172.30.230.151   172.21.34.237,my-svc.my-ns.svc.example.com   8080:31153/TCP      25m
```

I have another controller which can write `service.status.loadBalancer.ingress[].hostname` however it is reverted when metallb controller is running. As a feature request, I would like metallb to ignore hostnames on status and only work with  `ingress[].ip` instead, and leaves `hostnames` intact.

**Comment by fedepaol** [comment]
sounds like a bug more than a feature request :P

**Comment by hzilex** [comment]
I did some digging and found this in controller/service.go. It would clear all data below service.status.loadBalancer when converge balancer.

```
// clearServiceState clears all fields that are actively managed by
// this controller.
func (c *controller) clearServiceState(key string, svc *v1.Service) {
	c.ips.Unassign(key)
	svc.Status.LoadBalancer = v1.LoadBalancerStatus{}
}
```

**Comment by mlguerrero12** [comment]
Thank you @hzilex for your investigation. I'll be working on this.

**Comment by fedepaol** [comment]
@m-yosefpor just to make sure we got your issue right, the hostname part is still related to an ip provided by metallb, right?

**Comment by fedepaol** [comment]
Getting back here. I thought this was a requirement to interact with either the k8s_external plugin or k8s_gateway, but looking at their docs they seem to just work out of the box based on the service description.

So, what the real use case for having this extra field being set?

**Comment by m-yosefpor** [comment]
> just to make sure we got your issue right, the hostname part is still related to an ip provided by metallb, right?

@fedepaol Yes we set the hostname such that k8s_external can resolve those domains.


> So, what the real use case for having this extra field being set?

This does not affect the resolution functionality, and k8s_external or k8s_gateway resolution with svc-lb external IP works fine. However setting this extra field cause hostname to be shown when listing the services (e.g. with `oc get svc`) which is a user friendly feature (users can see the hostnames set for their services)

**Comment by m-yosefpor** [comment]
@fedepaol  I've just seen your comments on https://github.com/metallb/metallb/pull/1793#discussion_r1088082701, and yes the hostname is mutually exclusive and has nothing to do with the IP field. However, the current behavior of metallb which overwrites the whole `.status` part of the service, makes it hard for other external components to work along side metallb for adding extra functionality. In our case, we have another component to provide this `hostname <-> ip` status binding for better readability on user side, but metallb reverts everything.

**Comment by fedepaol** [comment]
If this is only for readabilty, I don't think it's worth the extra complexity that we might need to introduce in our codebase. MetalLB erases the status part because it is the loadbalancer in charge of that service and I don't think it's expected to have multiple controllers handling the ingress part of a lb service at the same time (that's why we have loadbalancer class).

I'd suggest using other approaches such as annotations / kubectl plugins for example. Closing the issue.

**Comment by soenkeliebau** [comment]
Sorry for raising this zombie, but we just hit this as well, just coming from a slightly different angle. So I thought I'd just drop this scenario here for reference.

In the Stackable Data Platform we have a listener-operator that reads a LoadBalancer Service's `.status.loadBalancer.ingress[]` and uses those addresses to mint TLS server certificates: 
- an `ingress[].ip` becomes an iPAddress SAN on the cert
- an `ingress[].hostname` becomes a dNSName SAN on the cert

What we are currently trying to achieve is have a stable human-readable fqdn as a separate hostname entry in the status, alongside the IP that MetalLB assigns. See below for an example:

```
status:
  loadBalancer:
    ingress:
      - ip: 172.21.34.237                 # owned by MetalLB
      - hostname: nifi.stackable.local    # owned by an external-DNS-style controller
```

The DNS name is registered and managed by a separate controller; MetalLB neither knows nor needs to know about it. The only thing we need is for that extra hostname entry to survive so the issued certificate is valid for the name clients actually connect to, not just for an ephemeral IP.

Because MetalLB rewrites the entire `ingress[]` array down to the entries it authored, it deletes the additional hostname entry on its next reconcile. I'd argue though, that the extra entry doesn't touch, conflict with, or duplicate the IP MetalLB manages. As a result the certificate ends up valid only for the IP, and the stable DNS name can never be carried through into the cert from the status. 

I understand the reasoning for MetalLB owning the IP it allocates, we don't want to interfere with this. But I think this use case is narrower than "multiple controllers managing the LB" which was mentioned as an anti-pattern in the discussion above. 
In this case the friction is, that MetalLB asserts ownership over fields and entries it never wrote. Preserving `ingress[]`entries that carry only a hostname (and no MetalLB-assigned IP), rather than clearing the whole list, would allow this composition without giving up MetalLB's authority over its own allocations.
