### ISSUE TITLE
Bogus neighbours in both address families

### ISSUE THREAD

**Issue by leppeK** [metallb/metallb#1736]
versions:
Kubernetes: v1.25.4
MetalLB: main at time of writing: https://github.com/metallb/metallb/commit/7c1a17eafcc6b6bace1271042143d01df11db2c9

When rendering the FRR config it also renders IPv6 neighbours for "address-family ipv4 unicast" and IPv4 neighbours for "address-family ipv6 unicast"

```
kubectl -n metallb-system exec speaker-82jw9 -itc frr -- vtysh -c"show bgp sum"

IPv4 Unicast Summary:
BGP router identifier 10.68.50.169, local AS number 4265547035 vrf-id 0
BGP table version 7
RIB entries 13, using 2496 bytes of memory
Peers 4, using 57 KiB of memory

Neighbor              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt
10.68.50.129          4 4265547010      4794      3456        0    0    0 02:35:34            0        7
10.68.50.161          4 4265547010      4794      3456        0    0    0 02:35:34            0        7
12a0:43b0:58b4:740::1 4 4265547010      4794      3456        0    0    0 02:35:34 NoNeg
12a0:43b0:58b4:741::1 4 4265547010      4794      3456        0    0    0 02:35:34 NoNeg

Total number of neighbors 4

IPv6 Unicast Summary:
BGP router identifier 10.68.50.169, local AS number 4265547035 vrf-id 0
BGP table version 1
RIB entries 1, using 192 bytes of memory
Peers 4, using 57 KiB of memory

Neighbor              V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt
10.68.50.129          4 4265547010      4794      3456        0    0    0 02:35:34 NoNeg
10.68.50.161          4 4265547010      4794      3456        0    0    0 02:35:34 NoNeg
12a0:43b0:58b4:740::1 4 4265547010      4794      3456        0    0    0 02:35:34            0        1
12a0:43b0:58b4:741::1 4 4265547010      4794      3456        0    0    0 02:35:34            0        1

Total number of neighbors 4
```

I suggest splitting up the templates to create ipv4 and ipv6 neighbours seperately.

**Comment by xhejtman** [comment]
+1

So far, we are using 0.12 version, I tested 0.13.7, however, it does not work as our BGP routers are split so that IPv4 handles IPv4 only connections and the same for IPv6, and MP sessions are rejected.

It would be good to make MP BGP configurable.

**Comment by fedepaol** [comment]
Trying to make some considerations around this.
In case of dual stack services, we require the service to be fed by the same pool.
This means that with the current configuration, we can't express "announce this only to the v4 peers, and that only to the v6 peers". This because all the announcement logic is tied to the pool.
So, in order to fix this we either need to add an "ipfamily" flag to the bgpadvertisement, or even better, decouple the source of the ip of the service in case of dual stack services, allowing a separate configuration of the ipv4 and ipv6 side of the same service, which can then be different.

I think the latter is cleaner even though it's gonna be a bit more painful to implement. In the meanwhile, a quick workaround is to split the service in two (one v4 only, the other v6 only) and to handle them separately. Using the bgppeer selector of the advertisement, it will be possible to advertise each family to the respective peer.

**Comment by fedepaol** [comment]
Closing this in favour of https://github.com/metallb/metallb/issues/1757
