### ISSUE TITLE
Dual stack services: feed from different addresspools

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1757]
Follow up of https://github.com/metallb/metallb/issues/1736 , where the request is to announce v4 addresses to v4 peers only and v6 to v6.

Copying the considerations from there:

>So, in order to fix this we either need to add an "ipfamily" flag to the bgpadvertisement, or even better, decouple the source of the ip of the service in case of dual stack services, allowing a separate configuration of the ipv4 and ipv6 side of the same service, which can then be different.
>I think the latter is cleaner even though it's gonna be a bit more painful to implement. In the meanwhile, a quick workaround is to split the service in two (one v4 only, the other v6 only) and to handle them separately. Using the bgppeer selector of the advertisement, it will be possible to advertise each family to the respective peer.

**Comment by fedepaol** [comment]
Leaving this as "maybe" since this will probably require a bit more thought.

**Comment by lujingyuan01-qianxin** [comment]
I recently encountered a similar issue. Due to limitations on the switch side, when attempting to establish a BGP peer using IPv4 addresses, having the IPv6 address family configured can cause BGP to malfunction. I hope for more flexibility in configuring the address family for neighbors.

May I inquire if there have been any recent developments regarding this issue?
