### ISSUE TITLE
Fallback to single stack if dual is not available

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1776]
Trying to collect here the ideas described in https://github.com/metallb/metallb/issues/1339 and https://github.com/metallb/metallb/pull/1590

- we should maintain the logic of having all the ips to a service coming from the same pool
- if the service is dual stack, we should favour the pools that are able to provide both ips first, and fall back to those providing only one, starting from the primary ip family and falling back on the secondary
- if the service is "RequireDualStack" and not "PreferDualStack" we should not allocate if there's no such pool that can provide both ips

**Comment by fedepaol** [comment]
cc @oribon @gclawes for a review on my considerations

**Comment by oribon** [comment]
seems good to me as the way to respect prefer/require dualstack while keeping the single pool per service relation.
we should consider what to do if a preferdualstack service gets a single ip (because there aren't dualstack pools at its creation) but later on a dualstack pool is added - should we reallocate its ips to that pool or keep it with a single ip?

**Comment by johanfleury** [comment]
Seriously those bots…

Please reopen.
