### ISSUE TITLE
Testing MetalLB on AWS Outposts Server LNI interface with EKS

### ISSUE THREAD

**Issue by FireballDWF** [metallb/metallb#1847]
I'm taking on testing the Layer 2 mode of MetalLB to provide LB services on the [Local Network Interface](https://docs.aws.amazon.com/outposts/latest/server-userguide/local-network-interface.html) (which provide Layer 2 including ARP protocol support) on [AWS Outposts Servers](https://aws.amazon.com/outposts/servers/) running worker nodes of an [Amazon EKS](https://aws.amazon.com/eks/) cluster.  Previously, I successfully tested the same config except used [k3s](https://k3s.io/)

Filing this ticket per https://metallb.universe.tf/installation/clouds/#can-metallb-support-my-cloud-provider while I can't provide direct access to Outposts Servers to external parties, I have direct access and I'm willing to run project tests, provide results, and generally collaborate with the project.

**Comment by dickeyf** [comment]
I am also interested in using MetalLB inside Amazon EKS on AWS Outpost.

However I am not certain whether LNI would be an option for me as we need other parts on the VPC to be able to connect to the LB.  Is my assumption right that IPs in the VPC won't be able to reach the MetalLB IP advertised via the LNI?


On my end, I am evaluating using EN2 Private IPs with MetalLB directly.  I would add a new "Mode" to the L2Advertisement: instead of using ARP, attach to the ENI the private IP.  This would require:
1. Create a CIDR reservation on the subnet in which the worker nodes are running.  This will allow forming a pool of IP that exists in the subnet, which won't be taken by EC2s or the VPC-CNI.
2. I configure a MetalLB pool using that CIDR reservation.
3. I create a L2Advertisement but add a new flag to it, which will change its mode of operation from "ARP" to "AWS-VPC".

Then what would happen is that an active speaker will not use ARP, but instead use AWS SDK to attach the private IP to one of the EC2's ENIs (It should be able to add new ENI if ENIs reached their IP limits, due to CNI).  Packets would then arrive at the host without needing ARP or BGP, and this would fully be compatible with VPC networking.

I am arranging with AWS to get access to Outpost for testing the integration of our product into EKS AWS Outpost, which requires Service Type LoadBalancer.

**Comment by FireballDWF** [comment]
@dickeyf Only the "Server" form factor of Outposts has LNI, if you will get getting access to a "Rack", then it does not have the LNI feature, Racks have the LGW (Local GateWay) feature, the main difference being LNI provides Layer 2 access (including ARP) to the "Customer network" while LGW only provides Layer 3.   

Given your desire for VPC based clients to access the LoadBalancer services, your approach from an AWS perspective (using ENI attachments as ARP is not supported within VPCs) sounds good.  

Would be happy to test and collaborate with you on you initiative as well.

**Comment by dickeyf** [comment]
@FireballDWF Awesome thanks for the clarifications about LNI!
I am indeed aiming for the "Rack" form factor of Outpost.  So I am more confident that I need to pursue my ENI attachment approach as it would integrate in all form of Outpost.

Any collaboration would be welcome!  I am also looking suggestions from the authors of MetalLB, in case they have any preferences on how this should be implemented.

**Comment by fedepaol** [comment]
Getting to the original question: we are open to list aws lni to the supported cnis, and we are not strict. If you say it works, just file the pr as we did for antrea https://github.com/metallb/metallb/issues/1455

And of course we are open to contributions and collaboration!

For the other part, I foresee more an external controller that does the binding of the vip associated to the service, so metallb remains focused on implementing the advertisement using routing protocols. You can leverage only the ipam part by adding a ipaddresspool without any advertisement.

**Comment by FireballDWF** [comment]
I have confirmed the Layer 2 mode on an LNI (Outposts Servers feature) works as expected.  I'm running a few more tests then will writeup my findings.

**Comment by sbrser** [comment]
> I have confirmed the Layer 2 mode on an LNI (Outposts Servers feature) works as expected. I'm running a few more tests then will writeup my findings.

@FireballDWF did you write it? Where can we find?

**Comment by FireballDWF** [comment]
I did not have to change any MetalLB code, want just a matter of configuration.  I don't have anything written up for public consumption.
