### ISSUE TITLE
Consider migrating webhook signing implementation via cert-manager

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#1868]
Although it is very convenient to have metallb signing the images, this opened a number of corner cases which I am not sure depend on how the cert controller library.
From what I can observe, the webhook failures are mostly caused by cluster / networking issues.
In any case, migrating to a well known solution such as cert-manager would mitigate the issues / allow our users to rely on all the troubleshooting material that cert-manager, being the de facto solution, provides.

Lastly, the helm charts already provide an option to disable the webhooks, I think we should provide manifests too.

**Comment by liornoy** [comment]
Can you please update whether is this still a desired change?
because I can see that on May 2022 we switched from cert-manager to the current cert-controller
https://github.com/metallb/metallb/pull/1360/commits/d26de122dd52b5b3e4201789505ccebba21946d5

related issues:
https://github.com/metallb/metallb/issues/1642

I will +1 for switching to cert-manager because this will allow us to omit the permission of the metallb-system:controller ClusterRole for validatingwebhookconfigurations and mutatingwebhookconfigurations, which is one of the security recommendations described here: [link](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-code-security-policy-reference/kubernetes-policies/kubernetes-policy-index/ensure-clusterroles-that-grant-control-over-validating-or-mutating-admission-webhook-configurations-are-minimized) 

Just to be clear, I'm not sure if the fact we have `resourceNames: metallb-webhook-configuration` resolves or reduces the severity of this.

**Comment by fedepaol** [comment]
Yep, the rationale is well described in the original post. Cert-manager is more battle proven, well known and accepted by the community. I did not like (and still don't) having it as a mandatory dependency.

**Comment by fedepaol** [comment]
Closing this, after the initial release we didn't hear too many complains about webhooks
