### ISSUE TITLE
Question: how to configure networkpolicies?

### ISSUE THREAD

**Issue by bh-tt** [metallb/metallb#1936]
I'm currently working through our clusters to implement networkpolicies, and ran into a problem: Metallb does not really document which ports have incoming traffic and which other cluster services it talks to. The controller has port 9443 as incoming webhook-server, I assume this traffic comes from the apiserver?

I'm assuming the speakers cannot use networkpolicies as they use host networking, so this is mostly about configuring networkpolicies for the controller.

So I have the following questions:
 - which incoming ports does the controller have, and from where are these accessed? (for ingress policies)
 - how does the controller communicate new configurations to the speakers? (for egress policies)

We should probably add the response to this issue to the FAQ on https://metallb.universe.tf/faq/.

**Comment by fedepaol** [comment]
> * which incoming ports does the controller have, and from where are these accessed? (for ingress policies)

The ports can be found in the https://github.com/metallb/metallb/blob/main/charts/metallb/templates/controller.yaml template. You'll have:
- the webhook port
- the secure metrics port / the port, depending on whether you want to enable the kuberbac proxy or not.


> * how does the controller communicate new configurations to the speakers? (for egress policies)

The controller doesn't communicate directly to the speaker. The speaker combines the configuration with the IP assigned to the service by the controller in order to drive its behaviour.
