### ISSUE TITLE
Replace validation webhook with CEL/OpenAPI native validation

### ISSUE THREAD

**Issue by howardjohn** [metallb/metallb#2182]
### Is your feature request related to a problem?

Kind of. Validation webhooks are annoying/complex to run and are a reliability issue.

### Describe the solution you'd like

Remove the `ValidatingWebhookConfiguration` and replace it with native CEL/OpenAPI validation.

A brief look at the current validation logic suggests this should be all fairly simple to do

### Additional context

Example of other projects doing the same: https://github.com/kubernetes-sigs/gateway-api/pull/2595 https://github.com/istio/istio/issues/46151 

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment]
I'd be happy to ditch the validation wh (and actually, we offer a knob to disable it with the helm deployment), for the very same reasons you listed (and https://github.com/metallb/metallb/issues/1597 is a testament to that).

However, MetalLB's validation takes care of the relation between different crds (i.e. duplicates, references to non existing resources) and I am not sure we could rely on observing only the single instance we are receiving in order to perform the same amount of tasks that metallb currently does.

I am open to  better documenting how to disable them both on helm and kustomize (and eventually flip the default value), but still having a way to enable them, as the validation carries some value intercepting misconfigurations that would be caught only in the logs / metrics.

**Comment by howardjohn** [comment]
Ah I think I only read a small subset of the current validation webhook logic so it seemed a lot simpler. Thanks for the extra context

**Comment by fedepaol** [comment]
@howardjohn based on the above considerations, I am closing this issue. Feel free to get back if I am missing something, but I think the current logic cannot be replicated with native validation.
