### ISSUE TITLE
ServiceL2Status follow-up: create resources in main namespace with speaker pod as OwnerRef

### ISSUE THREAD

**Issue by oribon** [metallb/metallb#2311]
### Is your feature request related to a problem?

https://github.com/metallb/metallb/issues/2158 is merged, but there's a corner-case we don't handle where if a speaker is deleted permanently (either the node is gone, or the user doesn't want it to act as a speaker) the l2 statuses that it created would be left dangling.

### Describe the solution you'd like

Since [cross-namespace owner refs are not allowed](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/), we think a reasonable approach would be creating the statuses in the same namespace as the speakers. When we do that, we can no longer use `servicename-node` as the resource's name, because multiple services with the same name can arrive from different namespaces.
So the idea is to have the statuses created with a generated name such as `GenerateName: <node-name>-` on the same namespace as the speaker, with the speaker pod being an ownerRef of the resource. Once a speaker is restarted / gone k8s will handle the deletion for us.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by oribon** [comment]
cc @lwabish :)

**Comment by lwabish** [comment]
Indeed.
Here are several things that occured in my mind:

1. I have met some situation like this before. We used a helm hook to trigger a job to gc crs because in my case the only way to install is from a helm chart.
2. Is it possible to detect speaker pod deletion with a mutating webhook, which could do some gc ?
3. When I implemented layer2status feature, It was a natual thought to put status cr in the same namespace with the service because from a user perspective, I may want to check the status of service and status cr simultaneously without switching namespaces back and forth. Of course, this is a quick summary of my personal opinion, and I look forward to hearing your thoughts.

**Comment by fedepaol** [comment]
> Indeed. Here are several things that occured in my mind:
>


If we can set an [owner reference](https://cluster-api.sigs.k8s.io/reference/owner_references.html?highlight=owner#owner-references) from the speaker pod itself to the status instance, then the gc will happen within kubernetes. 
 
>     1. I have met some situation like this before. We used a helm hook to trigger a job to gc crs because in my case the only way to install is from a helm chart.
> 
>     2. Is it possible to detect speaker pod deletion with a mutating webhook, which could do some gc ?
> 

This is not possible. It'd mean set a webhook on the path for all the pods (because webhooks are not namespaced iirc), which is not acceptable. Also, we learned to stay away as much as possible from webhooks (see https://github.com/metallb/metallb/issues/1597)

>     3. When I implemented layer2status feature, It was a natual thought to put status cr in the same namespace with the service because from a user perspective, I may want to check the status of service and status cr simultaneously without switching namespaces back and forth. Of course, this is a quick summary of my personal opinion, and I look forward to hearing your thoughts.

I agree that this feels more natural. However, having the status of what metallb does inside metallb's namespace doesn't sound too much of a stretch, especially if it solves the problem of the point before.

**Comment by lwabish** [comment]
Filtering pod from webhooks should not be a problem with the help of  [label selectors](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector) or [namspace selectors](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector).But I do agree that webhooks are tricky sometimes.

I'd love to follow your final advice and continue work on this improvement, but maybe will start a few days later if acceptable.

**Comment by fedepaol** [comment]
@lwabish just checking if you are still interested in helping with this. There is obviously no rush!

**Comment by lwabish** [comment]
> @lwabish just checking if you are still interested in helping with this. There is obviously no rush!
> 
> 

Yes I'd love to keep working on this.

**Comment by lwabish** [comment]
I 'll implement this maybe this weekend

**Comment by fedepaol** [comment]
Thanks a lot!

**Comment by jhoblitt** [comment]
Is it the weekend yet? :)

**Comment by fedepaol** [comment]
> Is it the weekend yet? :)

The pr was filed as you can see above :)
