### ISSUE TITLE
Add graceful-restart support

### ISSUE THREAD

**Issue by fedepaol** [metallb/metallb#2368]
### Is your feature request related to a problem?

Whenever a version of metallb is updated, the speakers are rolled one at the time. This is causing the behaviour described here https://metallb.universe.tf/concepts/bgp/#limitations to be amplified for each node of the cluster.

Graceful restart should mitigate this problem.

### Describe the solution you'd like

Either a per - peer graceful restart option, or a global one. To be discussed.
We should validate that all the proper signals are sent to the frr container and thus to the bgpd daemon (and e2e this), and cover the same feature in frr-k8s too.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by karampok** [comment]
Hi @fedepaol I can work on that. Thanks

**Comment by karampok** [comment]
Hi @aelbarkani, gracefull restart is helping to avoid happening any BGP change  when control plane FRR process is restarted (e.g. update image of the container), while the dataplane continues to work.

AFAICT graceful shutdown is when you want to stop for long the peering, and actually stop the traffic. But could you  expand? thanks

**Comment by aelbarkani** [comment]
@karampok the limitation I had in mind is when you remove a node from the cluster for maintenance or just for down scaling. Shouldn't be there a sort of signaling to the routers saying that the current node is going to shutdown so the routers can stop routing the traffic to it gracefully ? I suppose BFD protocol mitigates the problem partially by detecting the link failure very fast, but maybe it's a better solution to do it gracefully. Also, wouldn't this mechanism avoid the limitation described in the docs https://metallb.universe.tf/concepts/bgp/#limitations ?
`The consequence of this is that any time the IP→Node mapping changes for your service, you should expect to see a one-time hit where most active connections to the service break. There’s no ongoing packet loss or blackholing, just a one-time clean break.`.

By the way, I'm no network expert, so don't hesitate to challenge what I'm saying :).

**Comment by karampok** [comment]
okay, when you remove a node from the cluster you have to cordon/drain it first (`kubectl drain node`), that means any workload that is endpoint to your service will be removed from the node. If you have service trafficPolicyLocal then the frr process will stop advertising the routes instantly, when you have trafficPolicyCluster will happen the same (but this behavior  was added very recently https://github.com/metallb/metallb/commit/cbb36c74d1eb20495cd8b721c86bea7ed266da3f). In all cases the BGP peer will not have anymore routes towards the node. Existing tcp connection will break, but no new traffic will be blackholed.

> that any time the IP→Node mapping changes for your service
AFAICT this refers to the fact that the load balancing hashing mechanism of the peer (external router like juniper,cisco) might be impacted, e.g. client A that had a connection to  node X can switch to node Y just because node Z node was removed from the cluster.

**Comment by aelbarkani** [comment]
> In all cases the BGP peer will not have anymore routes towards the node. Existing tcp connection will break

Well this is what we want to avoid, breaking existing TCP connections. I had hoped the TCP sessions are not interrupted since this is what they say about BGP graceful shutdown:
```
Graceful shutdown migrates traffic from one BGP next-hop to another without interrupting the traffic flow
```
So my assumption was not accurate ?

**Comment by karampok** [comment]
The difference is that now we do "last-mile" BGP, our node is not a intermediate router forwarding traffic, is the end server that host the one side of the TCP connection. When we discuss trafficPolicyLocal, TCP connection will break simply because the one side of the connection stops, no way that can be avoided.

Now for trafficPolicyCluster you could argue that TCP connection from external client A to pod/EP B in k8s, which established through node X but reaches pod/EP B  in node Y,  could remain alive if node X is removed and simply traffic passes through another node Z. But multiple routes are already there,  no need for BGP shutdown, AFAIU it would be responsibility for the underlay CNI/network implementation to keep the maping between client A to pod/EP B stable independent from which k8s nodes the cluster enters. Which is interesting question but no very metallb related (I think)

**Comment by aelbarkani** [comment]
> Now for trafficPolicyCluster you could argue that TCP connection from external client A to pod/EP B in k8s, which established through node X but reaches pod/EP B in node Y, could remain alive if node X is removed and simply traffic passes through another node Z. But multiple routes are already there, no need for BGP shutdown, AFAIU it would be responsibility for the underlay CNI/network implementation to keep the maping between client A to pod/EP B stable independent from which k8s nodes the cluster enters. Which is interesting question but no very metallb related (I think)

You mean with mechanisms like the Maglev consistent hashing implemented in Cilium CNI ? https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#maglev-consistent-hashing

**Comment by karampok** [comment]
@fedepaol  should we close that issue?

**Comment by fedepaol** [comment]
yep, closing as fixed by https://github.com/metallb/metallb/pull/2386 and https://github.com/metallb/metallb/pull/2550
