### ISSUE TITLE
Remove the need for `metallb.universe.tf/allow-shared-ip` annotation

### ISSUE THREAD

**Issue by lizhipeng629** [metallb/metallb#2421]
### Is your feature request related to a problem?

Currently, to allow multiple services to share the same IP address, we have to explicitly use the `[metallb.universe.tf/allow-shared-ip]` annotation. This adds extra steps to our service configuration and complicates the management process.

### Describe the solution you'd like

I would like to propose a feature improvement to MetalLB that removes the necessity for the `[metallb.universe.tf/allow-shared-ip]` annotation and allows all IPs to be shared by services as long as their ports do not conflict. Additionally, it would be beneficial to have an option to configure which IPs need to be shared through a ConfigMap, rather than setting this annotation each time a service is created. This would simplify the configuration and reduce the complexity of managing shared IPs in our Kubernetes environment.

Instead of requiring the `[metallb.universe.tf/allow-shared-ip]` annotation, MetalLB should:

1. Automatically allow IP sharing for all services as long as there are no port conflicts.
2. Provide an option in the ConfigMap to specify which IPs should be allowed to be shared.

### I've read and agree with the following

- [x] I've checked all open and closed issues and my request is not there.
- [x] I've checked all open and closed pull requests and my request is not there.

**Comment by tylerauerbeck** [comment]
Is there a benefit to configuring this within a configmap and relying on implicit behavior where an IP may be shared without a service teams awareness instead of the more explicit behavior that the current annotation provides? This just feels like moving the area where it's managed (i.e. managing it within the configmap vs. explicitly creating the annotation when you want this behavior to occur).

**Comment by lizhipeng629** [comment]
If we manage this explicitly, creating a service first and then wanting to reuse the same IP later would require me to find the existing service using that IP and then modify the service to add annotations. This adds to my burden and introduces an extra step of modifying the old service, increasing the risk of changes. By using a configmap for implicit management, I can simply check the configmap to understand which IPs are being shared.

**Comment by lizhipeng629** [comment]
> Is there a benefit to configuring this within a configmap and relying on implicit behavior where an IP may be shared without a service teams awareness instead of the more explicit behavior that the current annotation provides? This just feels like moving the area where it's managed (i.e. managing it within the configmap vs. explicitly creating the annotation when you want this behavior to occur).

If we manage this explicitly, creating a service first and then wanting to reuse the same IP later would require me to find the existing service using that IP and then modify the service to add annotations. This adds to my burden and introduces an extra step of modifying the old service, increasing the risk of changes. By using a configmap for implicit management, I can simply check the configmap to understand which IPs are being shared.

**Comment by fedepaol** [comment]
Couple of observations:

- we should never ever use configmaps again. MetalLB has CRD support, and any behavior must be implemented through it
- sharing the IP poses some limitations on how the service should look like (especially in case of ETP=local), so I think it's fair to have it as an explicit property of the service. This allows a more predictable behavior
- if the shareability of an IP becomes a property of the IP (and not of the service), we flip completely the current logic where the focus is "I allow these services to share the IP" vs "I allow this IP to be shared". Also, it makes the ip assignement logic harder to follow as we'll have a pool of shareable IP and one of non shareable. And to force a service to pull a shareable one, you'd still need to add the annotation / spec.loadbalancerip, otherwise there won't be any guarantee the ip is a shareable one

All in all, I don't see this as a benefit worth the complexity that it would add to the current logic.

**Comment by fedepaol** [comment]
Closing this as not planned, as I wrote above I don't think it's worth pursuing

**Comment by mcarbonneaux** [comment]
Why not be abel to disable the sharing key mécanisme ? Nodeport do not control if you've set sharing key to abel to share an ip with différent port / protocol... Settings an annotations do not block trying to use thé same ip/port/protocol ... And oblige to modify the first service that had take the ip to permit to share it... And is thé same has who take first ip/port/protocol has the it ... Why adding more complexity ?

Add global configuration to abel to disable this.
