### ISSUE TITLE
Creating NDP responders returns errors for a long time after interface comes up

### ISSUE THREAD

**Issue by danderson** [metallb/metallb#248]
With the new all-interfaces listening code, NDP responders are created for every interface on a machine, including the virtual ones going into containers.

For some reason, on minikube, binding to those interfaces continues to fail for 10-60s after the interface is brought up and given a link-local address (which are the two things we test for before creating a responder).

Sample error:

```
{"caller":"announcer.go:93","error":"creating NDP responder for \"veth1755bdb\": listen ip6:ipv6-icmp fe80::f0af:49ff:fe87:f134%veth1755bdb: bind: invalid argument","interface":"veth1755bdb","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2018-04-20T02:34:30.667836249Z"}
```

The interface status seems unchanged during/after the errors:

```
$ ip addr show veth1755bdb      
105: veth1755bdb@if104: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether f2:af:49:87:f1:34 brd ff:ff:ff:ff:ff:ff link-netnsid 7
    inet6 fe80::f0af:49ff:fe87:f134/64 scope link 
       valid_lft forever preferred_lft forever
```

So, it's unclear to me why this would be an invalid bind, based on information available here...

**Comment by JoshuaAndrew** [comment]
@danderson 

I came cross this error too.

Sample error:
```
{"caller":"announcer.go:93","error":"creating NDP responder for \"ens160\": listen ip6:ipv6-icmp fe80::b9b2:4ba0:f192:6302%ens160: bind: cannot assign requested address","interface":"ens160","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2018-04-26T06:44:01.802580609Z"}
{"caller":"announcer.go:93","error":"creating NDP responder for \"ens160\": listen ip6:ipv6-icmp fe80::b9b2:4ba0:f192:6302%ens160: bind: cannot assign requested address","interface":"ens160","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2018-04-26T06:44:11.804347459Z"}
{"caller":"announcer.go:93","error":"creating NDP responder for \"ens160\": listen ip6:ipv6-icmp fe80::b9b2:4ba0:f192:6302%ens160: bind: cannot assign requested address","interface":"ens160","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2018-04-26T06:44:21.80710902Z"}
{"caller":"announcer.go:93","error":"creating NDP responder for \"ens160\": listen ip6:ipv6-icmp fe80::b9b2:4ba0:f192:6302%ens160: bind: cannot assign requested address","interface":"ens160","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2018-04-26T06:44:31.808671189Z"}
{"caller":"announcer.go:93","error":"creating NDP responder for \"ens160\": listen ip6:ipv6-icmp fe80::b9b2:4ba0:f192:6302%ens160: bind: cannot assign requested address","interface":"ens160","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2018-04-26T06:44:41.812762075Z"}
{"caller":"announcer.go:93","error":"creating NDP responder for \"ens160\": listen ip6:ipv6-icmp fe80::b9b2:4ba0:f192:6302%ens160: bind: cannot assign requested address","interface":"ens160","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2018-04-26T06:44:51.816335191Z"}
```

Environment:
- MetalLB version: 0.6.1
- Kubernetes version: 1.9.x

**Comment by mdasraf** [comment]
@danderson

Do we have a fix for this error?

**Comment by mslee89** [comment]
I have the same problem.
Has anyone solved this problem? 

Environment:
- MetalLB Version : 7.3
- Kubernetes version : 1.12.1

**Comment by spuder** [comment]
NDP is for ipv6 addresses. If you aren't using ipv6 those errors are probably harmless. 

https://metallb.universe.tf/concepts/
>In layer 2 mode, one machine in the cluster takes ownership of the service, and uses standard address discovery protocols (ARP for IPv4, NDP for IPv6) to make those IPs reachable on the local network. From the LAN’s point of view, the announcing machine simply has multiple IP addresses.

**Comment by tonytjo** [comment]
Dear All,

Just for all your information in case you encounter similar issue.

I have a 3-node bare-metal K8S cluster, with Flannel installed.
The 3 nodes have 172.31.34.0/24 and 172.31.35.0/24 networks attached.
I would like to have MetalLB to provide LB IP for both networks, using L2 mode.

However, from the logs in the speaker containers, I found that MetalLB only creates responder in ens192 (it is of 172.31.35.0/24 network) network.
And as a result, I can get LB IP for 172.31.35.0/24 network and can access to it successfully.
For 172.31.34.0/24 network, I can also get an IP from MetalLB, but in fact the IP cannot be reached by other machines.

Finally I have traced the source codes.
Here in the code:
https://github.com/metallb/metallb/blob/5fff8b37444fc11b4bce3a6c2ac6cfedb479e4a2/internal/layer2/announcer.go
Line 109
If "failed to create NDP responder", it will "return".

As a result, since MetalLB failed to create NDP responder on the ens192 interface, and then returned, and so did not create ARP responder for other interfaces.
I "fix" the problem by disabling IPv6 in all interfaces, because in my environment there is no need of IPv6.

Regards,
Tony

**Comment by jamesdube** [comment]
> Dear All,
> 
> Just for all your information in case you encounter similar issue.
> 
> I have a 3-node bare-metal K8S cluster, with Flannel installed.
> The 3 nodes have 172.31.34.0/24 and 172.31.35.0/24 networks attached.
> I would like to have MetalLB to provide LB IP for both networks, using L2 mode.
> 
> However, from the logs in the speaker containers, I found that MetalLB only creates responder in ens192 (it is of 172.31.35.0/24 network) network.
> And as a result, I can get LB IP for 172.31.35.0/24 network and can access to it successfully.
> For 172.31.34.0/24 network, I can also get an IP from MetalLB, but in fact the IP cannot be reached by other machines.
> 
> Finally I have traced the source codes.
> Here in the code:
> https://github.com/metallb/metallb/blob/5fff8b37444fc11b4bce3a6c2ac6cfedb479e4a2/internal/layer2/announcer.go
> Line 109
> If "failed to create NDP responder", it will "return".
> 
> As a result, since MetalLB failed to create NDP responder on the ens192 interface, and then returned, and so did not create ARP responder for other interfaces.
> I "fix" the problem by disabling IPv6 in all interfaces, because in my environment there is no need of IPv6.
> 
> Regards,
> Tony

Thanks, i had to diable ipv6 on the interface

**Comment by weizhouBlue** [comment]
I also encounter this ,    when  I intend to setup an dual-stack environment ， and create an ipv6-only  service
the assigned ipv6 loadbalancer ip does not take effect and fail to respond the NDP request

the speaker report error:
{"caller":"announcer.go:114","error":"creating NDP responder for \"ens192\": listen ip6:ipv6-icmp fe80::fb2d:382b:cdec:89cc%ens192: bind: cannot assign requested address","interface":"ens192","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2021-09-23T06:54:23.739737094Z"}

BTW,  I  assinged  an IPv6 address on the ens192 interface by manual ,  and the interface does work for ipv6

**Comment by godzilla-s** [comment]
> ve traced the source codes.

I have the same issue, you said you dsiable ip6 to fix it, it had any other problem?

**Comment by tonytjo** [comment]
> > ve traced the source codes.
> 
> I have the same issue, you said you dsiable ip6 to fix it, it had any other problem?

Yes I just disabled ipv6 in the worker nodes (i.e. the Linux OS level), then the problem has gone.

Hope you could also fix it by this method.

**Comment by blieb** [comment]
Hope there is also a real solution for this issue, because disabling ipv6 is not an option for me.

**Comment by john-a-joyce** [comment]
I think I may also be hitting this issue.  I am trying to test some dual-stack scenarios.  So disabling IPv6 is not an option.  I am using:
Kind version:  kind v0.17.0 go1.19.2 linux/amd64
Kind image:  kindest/node:v1.21.1
metallb version:  v0.11.0  

The failure message is:  
{"caller":"level.go:63","error":"creating NDP responder for \"veth00440d13\": listen ip6:ipv6-icmp fe80::6446:a5ff:fe61:11bf%veth00440d13: bind: cannot assign requested address","interface":"veth00440d13","level":"error","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2022-12-01T22:13:46.166036586Z"}

I believe due to another metallb issue I believe anything above v0.11.0 will not work for my dual stack case. 

Also in my case this issue never resolves,  but since I am trying to use IPv6 an NDP responder is required.

**Comment by fedepaol** [comment]
https://github.com/metallb/metallb/pull/1726 _might_ fix the issue. @john-a-joyce , would you mind trying to deploy directly from main? Also, note that now the configuration is crd based.

**Comment by john-a-joyce** [comment]
@fedepaol - Thinking a bit more my case is probably different, but appreciate any wisdom you might be able to share.    I think the initial failure is blocking me,  not that the initial failure is causing a premature exit.   Some more details.  The only failures I see in the speaker logs are related to the NDP responders for the Loadbalance IPv6 addresses that have been assigned to a service.   The veth noted in the message correspond to the workloads backing the service.   So IOW i really do need an NDP responder on that veth or AFAIKT my case will not work.    

I assume the "bind: cannot assign requested address" part of the error is what docker is telling the speaker,   but I can't figure out why docker is returning that unless maybe I am missing some IPV6 enable config somewhere (maybe docker daemon)

**Comment by fedepaol** [comment]
> @fedepaol - Thinking a bit more my case is probably different, but appreciate any wisdom you might be able to share. I think the initial failure is blocking me, not that the initial failure is causing a premature exit. Some more details. The only failures I see in the speaker logs are related to the NDP responders for the Loadbalance IPv6 addresses that have been assigned to a service. The veth noted in the message correspond to the workloads backing the service. So IOW i really do need an NDP responder on that veth or AFAIKT my case will not work.
> 
> I assume the "bind: cannot assign requested address" part of the error is what docker is telling the speaker, but I can't figure out why docker is returning that unless maybe I am missing some IPV6 enable config somewhere (maybe docker daemon)

even though those veths correspond to the endpoints of the service, those are not the interfaces metallb should / will reply from. That's because the arp request will come from a "real" node interface which is the one the traffic will reach the node from. From the node's host network to the pod is up to the cni.

**Comment by john-a-joyce** [comment]
Update on this for anyone that might find it useful.  I am now sure that I was not hitting the issue described here.  The bind failures in the logs MAY have cleared up when I set "ipv6: enable" in my docker daemon.json config file.   I have also found that one of the cases I was testing (an istio ingress) is not properly handling dual stack traffic.  So it is also possible the bind errors in the logs were a red herring for my env.
