### ISSUE TITLE
[Feature Request] Auto Host Labelling functionality

### ISSUE THREAD

**Issue by BloodyIron** [metallb/metallb#2498]
### Is your feature request related to a problem?

It's a touch manual to determine which node has any IP that MetalLB is doing ARP/other broadcasting for, and having this as node labels (as an option you can turn on) would be helpful for when we need to know this information.

### Describe the solution you'd like

Inspired by kube-vip's "enable_node_labeling" Environment Variable, it would be nice to have a function we could turn on/configure so that k8s nodes get labelled with which IP they are the leader for, or other similar scenarios.

In my case I use ARP Layer 2 for a single IP and I want to know sometimes which k8s host/node is announcing that IP without having to look at ARP broadcasts and cross-reference MAC Addresses for each node. I suspect this functionality would be useful for other people with more elaborate setups than mine.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by oribon** [comment]
Hey, we implemented the [ServiceL2Status](https://github.com/metallb/metallb/blob/main/design/crd-status.md#service-announcement---l2) resource lately, which solves exactly this problem :)

**Comment by BloodyIron** [comment]
> Hey, we implemented the [ServiceL2Status](https://github.com/metallb/metallb/blob/main/design/crd-status.md#service-announcement---l2) resource lately, which solves exactly this problem :)

Uhh if I'm reading that right, it's centric to Services and not so much the IP/CIDR that is being ARP Layer2 broadcasted. In my case I would have... all?... services go through a single node. Wouldn't that lead to a very large amount of labels being added? Or am I misunderstanding/misreading?

**Comment by oribon** [comment]
there are no labels, a ServiceL2Status is created for each advertised service saying which node hosts it. I thought you're talking about a case where you would have only one service, so that it'll be enough to only inspect the single resource to understand which host is in charge. 
In general, the status does not have a field for the IP, but I guess it could be expanded to have one. then it'll be possible to also understand the mapping between nodes and IPs, instead of just between nodes and service names as it is today.

**Comment by mdbooth** [comment]
I would also like this feature. My use case:

I am a provider of Kubernetes on OpenStack. I would like to enable my users to expose loadbalancer services with MetalLB. My users have OpenStack port security enabled on all Kubernetes nodes, which permits only expected ingress traffic. I would like to write orchestration to configure OpenStack port security with the expected MetalLB ingress traffic.

It has been discussed before, and I am aware that MetalLB is not interested in adding provider-specific code. My ask is that MetalLB exposes sufficient metadata to allow an external orchestrator to be written efficiently. I would like to ensure that any orchestrator works equally well with both L2 and BGP modes.

Any orchastrator will take the form of a controller running in the same cluster.

My best idea currently is to reconcile both BGPAdvertisements and L2Advertisements into an annotation on Nodes. Something like for the default pool:
```yaml
annotations:
  ip-allocations.openstack.metallb.universe.tf/default: 1.2.3.4,4.3.2.1,dead::beef
```

In a naive but still useful implementation the IP list would consist of all ingressIPs from all Services annotated with[^1]:
```yaml
annotations:
  metallb.universe.tf/ip-allocated-from-pool: default
```

[^1]: This can't be done efficiently in a k8s query, btw, because you can't filter on annotations. I can probably make it not suck completely with a custom field indexer running client-side.

In this naive but still useful implementation this same annotation would be added to all Nodes matched by the `default` pool's NodeSelectors[^2].

I would then write a second controller which reconciles Nodes with these annotations. It would add appropriate OpenStack port security rules to allow ingress traffic on IP addresses being served.

There are a bunch of improvements which could be made to this scheme, e.g. restricting to only nodes which are actually serving an IP rather than all IPs, and including port information. However, the important things to note are:
* The first controller is not provider specific. It knows nothing about OpenStack.
* The first controller could likely be implemented much more efficiently by internal MetalLB controllers which already have all of this state.

If MetalLB was able to expose this metadata natively I could write a much more robust solution which could also be re-used by other cloud providers.

[^2]: Which incidentally are label selectors rather than [NodeSelectors](https://github.com/kubernetes/kubernetes/blob/03fe89c2339a1582733649faab5f5df471f65f09/pkg/apis/core/types.go#L2914-L2921). These would be much more flexible if implemented as NodeSelectors.

**Comment by fedepaol** [comment]
@mdbooth iiuc, you are interested in understanding which nodes are advertising which service (or, from a given node perspective, which services it is advertising). Is that correct? If so, seems like a good use case for the advertisement status crds (https://github.com/metallb/metallb/blob/main/design/crd-status.md). 
It's currently implemented for l2 only but now that we have that implementation, extending the bgp one shouldn't be super terrible.

You'd then need some gymnastic (and some indexes on the local caches) to retrieve the service and then the ports, but seems doable.

**Comment by mdbooth** [comment]
I did notice that, but I assumed that as it's not implemented for BGP it was an internal implementation detail. If you intend to implement this for BGP too then this might be a good way to go. The queries for all services on a Node would not be pretty, but as you say could be fulfilled by a local informer so are likely fine in practise.

I assumed that for BGP a service can be exposed on multiple nodes concurrently. Is that not the case? If it is the case, what would it look like in that scheme?

**Comment by fedepaol** [comment]
> I did notice that, but I assumed that as it's not implemented for BGP it was an internal implementation detail. If you intend to implement this for BGP too then this might be a good way to go. The queries for all services on a Node would not be pretty, but as you say could be fulfilled by a local informer so are likely fine in practise.
> 

It's formally defined and we have an issue to track the implementation https://github.com/metallb/metallb/issues/2157

> I assumed that for BGP a service can be exposed on multiple nodes concurrently. Is that not the case? If it is the case, what would it look like in that scheme?

The idea is to have one status per node, with the name of the node as part of the name plus labels to allow easy selection of either all nodes for a service or all services for a node (more or less what is being described [here](https://github.com/metallb/metallb/blob/main/design/crd-status.md#service-announcement---bgp), with the addendum that we should check what was done for l2 status which might have found some better ways to implement (iirc the name is autogenerated, for example).

**Comment by BloodyIron** [comment]
I'm interested in which nodes are ARP advertising which IP, not the services behind it. Just to clarify.

**Comment by fedepaol** [comment]
> I'm interested in which nodes are ARP advertising which IP, not the services behind it. Just to clarify.

well if you know which service is being advertised by which node, then you can retrieve the ip. Or if the double get is too much, we can think to denormalize and extend the status crd with the details of the ip (to be discussed).

**Comment by BloodyIron** [comment]
> > I'm interested in which nodes are ARP advertising which IP, not the services behind it. Just to clarify.
> 
> well if you know which service is being advertised by which node, then you can retrieve the ip. Or if the double get is too much, we can think to denormalize and extend the status crd with the details of the ip (to be discussed).

That's not what I want. I just want to know what IP(s) are being handled by MetalLB per node. I don't care about what services go through each IP. You're telling me I want something different, when that's not what I want.

There's a cluster relevant to this function that only has one inbound IP and everything goes through it. I would want to know what node has the IP because I already know everything goes through it. I don't care what node all the services are listening on.

**Comment by fedepaol** [comment]
What I am saying is that the same information you are looking for (ips per node) can be retrieved with the information you have available today, which is l2 advertisement status + service.
There is no plan to implement it in another way.

**Comment by BloodyIron** [comment]
> What I am saying is that the same information you are looking for (ips per node) can be retrieved with the information you have available today, which is l2 advertisement status + service. There is no plan to implement it in another way.

I do not agree... but this isn't my github so do whatever I guess... never mind...
