### ISSUE TITLE
Add an option to pass a list of interfaces to create announcers on

### ISSUE THREAD

**Issue by RostyslavFridman** [metallb/metallb#277]
At the moment layer2 mode creates ARP and NDP announcers on all interfaces that are up and of broadcast type.
However, it might be better to have an ability to pass a list of interfaces to create announcerson as a configuration option.
Due to the current code limitations it can be done only as an option passed to the metallb executable itself, not as a ConfigMap option.

Thus, I propose to:

- Add an optional argument to the metallb executable with a list of comma-separated interfaces to create ARP and NDP announcers on
- Pass these interfaces to `updateInterfaces()` method
- Make a decision, whether to create announcer with a condition
```
if len(a.bindInterfaces) > 0 && !isBindInterface(ifi.Name, a.bindInterfaces) {
	continue
}
```

**Comment by RostyslavFridman** [comment]
We have a custom configuration with multiple VLAN interfaces on kubernetes nodes. It doesn't seem like a good idea to listen on all interfaces from security perspective.

Moreover, due to implementation specifics openvswitch needs two interfaces for VLANs to work. When metallb sends ARP requests, it sends them from both of these interfaces and node can't decide where to send traffic. This effectively breaks load balancing.

**Comment by kfox1111** [comment]
I'm in the same boat.

**Comment by danderson** [comment]
Thanks for the details. I have some thoughts.

First, you won't gain anything from a security perspective. Kubernetes itself will happily handle traffic for the service IP no matter where the packets come from. The only change MetalLB makes is that well-behaved clients on those other networks can find the service IP, if the network config is compatible (i.e. they're in the same subnet as the service IP. An attacker can still just edit their ARP neighbor tables by hand and successfully contact the service IP. So, there's no security benefit to restricting the listening interfaces.

The setup you have that breaks LB is interesting. Could you give me more info about that, like `ip addr` on the machine that shows the two conflicting interfaces?

Again, I'm trying to figure out if there's a way we can make your situation work without adding another configuration option. This is especially important to me because people will think that it gives them security, when that is 100% not true... So then I'll get even more bugs that the "security options" are broken.

If we _must_ add this option, then I have a strong preference for building it into the config, not adding a commandline flag. This requires a bit of refactoring of the codebase to support dynamically adding/removing listening interfaces, but that means there's only one place for configuration.

**Comment by kfox1111** [comment]
Like everything security related, "security" is not a boolean. its a journey and you decide how much of it to take. But on the journey, in order to increase security (non boolean), not broadcasting unneeded info, and at least not responding for requests for unneeded info are better security. The other issue you raised can be mitigated via properly configured iptables rules. I'd like to be able to do all of the above.

As far as breaking things, I don't think it exactly will break anything, but... I have seen switches that have rather primitive arp table hardware. If vlans are involved, the one and only arp table entry can flip a vlan value around if it sees it on multiple vlans. This trashing of the arp table around will have a performance impact as it will act like the arp entry was dropped so many arp requests will have to be reissued. I don't know if any "modern" switches do this, for some definition of "modern". but, yet another possible reason to allow interface to be specified.

**Comment by kfox1111** [comment]
One more use case here.... I had a bunch of old bmc's that would crash/reboot randomly if they saw too many different arps in a given amount of time, so extra arp's on unexpected networks can cause bad things to happen.

**Comment by danderson** [comment]
Okay, I'm reluctantly convinced that there is a need for this. However, we should implement this through the configuration, not through a commandline flag. Right now MetalLB does not require any customization to its manifests to run, and I really want to preserve that property.

How about adding an interface field to the config, where "" means "all interfaces", and altering the speaker+layer2 code to only start listening once the config is loaded (and use the config-specified interface whitelist when it does) ? Likewise, updates to the config should update the list of listening interfaces, so that dynamic reconfiguration is possible.

I could live with that kind of implementation: layer2 is still zero-config in simple setups, more complex setups are trivially possible with a config edit, and going to the more error-prone configuration is an explicit step the user takes, so it should be clear to them why things aren't working properly ("why is MetalLB ignoring ARP on this interface?! Oh, because I configured it to ignore ARP").

WDYT?

**Comment by Jc2k** [comment]
I don't know if this is what you mean but would it be possible to have the `interfaces` setting on the address pools so that it only advertises addresses on the segment where they are actually routed/available? (With the default being "" as you described).

**Comment by joejulian** [comment]
Configuring the interfaces in the config could be problematic if the machine configurations are not heterogeneous, which they may not be: arm storage boxes, tensorflow systems, GPU. Each may have a different configuration, distro, etc. Some may have multiple interfaces, some may be bonded, some may be bridges and all may be in the same cluster.

Shouldn't we use the tell-me address of the arp request to do a route lookup and only reply on interfaces which have a route to the requester?

For example (this won't work since it uses the wrong source IP):
```go
	// Ignore ARP requests from hosts that cannot reach us on this interface
	routes, err := netlink.RouteGet(pkt.SenderIP)
	ok := false
	for _, route := range routes {
		iface, err := net.InterfaceByIndex(route.LinkIndex)
		if err != nil {
			a.logger.Log("route", route, "error", err, "msg", "failed to match route interface index to interface")
		}
		if bytes.Equal(iface.HardwareAddr, a.hardwareAddr) {
			ok = true
			break
		}
	}
	if !ok {
		return dropReasonUnreachable
	}
```

**Comment by GoelDeepak** [comment]
I agree with @joejulian. Route lookup is probably the right thing to figure out the correct interface. One less parameter and support for a cluster with heterogeneous machines.

**Comment by brandond** [comment]
I'm watching this one as well, hoping to use this with k3s running on a dedicated data plane interface separate from my management network. I don't see why it should be advertising on interfaces that I don't want to pass traffic on.

**Comment by adampl** [comment]
@joejulian If it understand you right, then your solution applies only to replies to ARP requests. What about the broadcasted "gratuitous ARP" announcements? I don't want them to be sent to all interfaces.

@danderson This feature is really important. Believe me, it's harder to convince a sysadmin to accept anything that broadcasts frames across all interfaces.

**Comment by danderson** [comment]
I'll say this one last time, because there seems to be some confusion here: **changing ARP listening interfaces has zero effect on the security of the system**. Please stop justifying this change on the basis of security, because on that basis, I should just close this bug as wontfix.

The on-node Kubernetes agent (kube-proxy, or kube-router, or possibly cilium in some configs) will forward packets destined for service IPs no matter what interface they came in on. All it cares about is "I received a packet from anywhere that isn't the local machine, and the destination IP is the service IP".

As a result, it does not matter what the ARP behavior of the system is. If you assume only correctly-configured clients, then you'll only get ARP requests on the correct interface(s) for the traffic. If you assume hostile clients, they can trivially discover and hardcode MAC addresses to transmit to the k8s nodes, and they are _guaranteed_ that the k8s node will handle that traffic.

Regardless of ARP behavior on the system, the actual "don't talk to unexpected hosts" security comes entirely from the routing configuration on the k8s nodes. The only way to guarantee that you'll never handle inbound traffic from the "wrong" interface is to configure strict reverse path filtering on the network stack. Alternatively, you can trust that "incorrect" inbound packets will be misrouted on the way back out, so two-way communication will be impossible. Either way, again, the ARP behavior of the system doesn't change what a hostile entity on your network can do to your k8s cluster. The on-node routing and network stack configuration is what can do that.


Now, with that out of the way... What _are_ valid reasons for this change?

 1. The way we listen for ARP traffic means that we receive an ARP request multiple times when "complex" interfaces are involved (bridge, vlan, macvlan). Ideally, it would be possible to detect and correctly handle all those interface types, but in practice, it's not always possible to figure out what the cluster administrator _wants_ to have happen.
 2. Failover ARP spam broadcasts on all interfaces. While again, this is not a security problem in any way, it can confuse dumb networking gear with broken firmware, causing loss of connectivity.
 3. Listening on all interfaces leads to a lot of logspam on Kubernetes clusters, because most network addons create one veth pair for each pod. There's no value in listening for service ARP on those interfaces, but we can't know that, so we have to listen on dozens of useless interfaces. Again, not a problem on a technical level, but it's inelegant.

The first two are what we really need to address. The third is nice to have, but not very relevant.

The route-based suggestion of @joejulian only addresses 1. When we have to do ARP broadcast on failover, we don't have any idea what a good source address would be for a routing lookup. The only other option would be to reverse engineer the routing configuration of the system, and try to "manually" reproduce what the kernel does when attempting to make a decision. That's never going to work out, because linux policy routing let sysadmins do extremely complex things, and we'll definitely get it wrong if we try to emulate the kernel's behavior.

That leaves us with some variant of the original suggestion: explicitly specify a list of interfaces to listen on, and only listen on those. The constraints/problems with that are:

 1. If we require listening interface configuration unconditionally, this complicates L2 mode setup. Currently, L2 mode is zero-config for simple setups (e.g. small homelab, simple prod cluster), and this is a nice property.
 2. If we require listening interface configuration conditionally (i.e. default to "all interfaces" if not specified), then there will still be the support burden of "metallb doesn't work!" caused by either complex interface setups or broken network equipment. These are hard to troubleshoot, so maybe the simpler thing is actually to require a little bit of upfront configuration, to save on headaches later.
 3. Heterogeneous clusters would require a different listening interface configuration on different machines (e.g. listen on eno1 on simple compute nodes, but enp3s5 and vlan6 on "gateway" nodes). We must be able to express such configurations for those who need it, without overly complicating the configuration for those who don't.
 4. Kubernetes is not friendly to heterogeneous pod configurations for DaemonSets. This means it's significantly more difficult to solve this with commandline flags, because as soon as you require different flags for different machines, you need to customize manifests a whole bunch, which opens up more risks of operator error. This suggests it would be better to have this configuration with MetalLB's own configuration, because that means the k8s configuration is trivial ("run this pod on every node"), and the complexity is just in what we tell each pod to do.

Given all this, what solution does this suggest?

 1. _Require_ listening interface configuration in L2 mode. L2 mode will be slightly less magical, but reducing the support burden is more important to me. We'll have to make sure that it's possible to upgrade from 0.8 to 0.9 gracefully. Maybe we can "default to all" as a transition step, so it's possible to safely upgrade the binaries and then edit configurations.
 2. Place listening interface configuration in MetalLB's configuration, with the rest of the settings that influence what MetalLB does.
 3. Support using `nodeSelector` fields to assign different listening configurations to different machines. Speakers already have logic to handle node selectors in BGP mode, so the main question is "config syntax", implementation should be easy.
 4. Listening interface configuration needs to be per-address-pool. This is needed because we're trying to not confuse buggy network gear when doing ARP broadcasts, so in (unusual) configurations where there are multiple L2 mode pools that service different interfaces, we cannot broadcast on the union of both. We have to be precise on a per-pool level about where we're advertising.

Thoughts on config syntax coming in another post, but, how does the above sound? As a bonus, if you still don't believe me about the security argument, all this accidentally gives you the false sense of security you wanted anyway! :P

**Comment by danderson** [comment]
In the configuration, we have two conflicting objectives:
 1. Simple configurations should not require more than just a `interfaces: ["eno1"]` config entry. 
 2. Complex configurations need a format that's more painful to enter: a list of (interfaces, nodeSelector) pairs.

A solution to that is to have a global "interfaces" setting for simple configs, and a complex per-pool "interfaces" setting for complex configs. The final config is the union of the two, where the global config applies to all pools and all nodes.

A simple config would look like:

```yaml
layer2-config:
  interfaces: ["eno1", "eno2"]
address-pools:
  - name: default
    mode: layer2
    addresses:
      - 10.0.0.10 - 10.0.0.100
```

A complex config would look like:

```yaml
address-pools:
  - name: default
    protocol: layer2
    addresses:
      - 10.0.0.5 - 10.0.100.10
    interfaces:
      - interfaces: ["eno1", "vlan6"]
        node-selectors:
          - match-labels:
              rack-name: foo
          - match-labels:
              rack-name: bar
      - interfaces: ["eno2"]
        node-selectors:
          - match-labels:
              rack-name: quux
```

In the complex config, the `interfaces` sections are additive: each node listens on the union of all interfaces that were selected by _any_ of the node selectors. An empty node selector means "all nodes". This makes it easy to express configs like "listen on eno1 everywhere, and also on vlan6 on specific machines."

**Comment by adampl** [comment]
Thanks for the detailed analysis. Yet I'm not quite convinced if a fully centralized config is the safest approach. It may simplify config for multiple identical nodes, but in such cases people usually create nodes from predefined templates or using other automation tools. I'd prefer a simple per-node config, attached to the node itself (possibly in a JSON annotation), and here's why:

Imagine you add a node to an already pretty complex, heterogeneous cluster. Now you have to inspect all of the config rules to make sure that this node won't match any unwanted selector of all the already defined selectors - and if it does, modify these selectors (or labels, or both), and then check again and again. I'm afraid the complexity of this problem grows somewhat exponentially.

The other benefit would be that once you remove a node, its config disappears with it, so you don't have to worry about removing it from the common `ConfigMap` (garbage collection). Also, interfaces are usually added to (or removed from) one node at a time, so I'd prefer to avoid checking/changing some central config every time I do so.

For me, the only drawback of annotations is that they are strings, so we'd have to put there a JSON. However it's already a common practice in other projects.

Anyway, regardless of the approach you choose, I'd recommend to organize the interfaces in pools, similar to the address pools. Then in the address pool config we would just list the interface pool names. There would be a built-in pool `all` (or `default`, `*`, whatever) containing all interfaces in all nodes, and this would be the default value - at least in the transition period, though I think it's OK to keep such defaults.

Please let me know what you think :)

**Comment by kfox1111** [comment]
Both would be best. Cluster wide defaults for interface, but overridable at the node level. I have clusters where most of the nodes are the same, but with a few outliers. For example, think base pool of compute with a few gpu nodes in the pool that are a different type of hardware. Only having to override the outliers would be easiest to manage.

**Comment by kfox1111** [comment]
@danderson kubecon had an interesting keynote about thinking from an attackers perspective that's worth a watch: https://www.youtube.com/watch?v=3jGNjan6I3Y&list=PLj6h78yzYM2NDs-iu8WU5fMxINxHXlien&index=278&t=0s - Keynote: Hello From the Other Side: Dispatches From a Kubernetes Attacker - Ian Coldwater

**Comment by HaveFun83** [comment]
We run into a similar issue. 
Our worker nodes have two interfaces where only one has a layer 3 connection. 
The second has only L2 connection and is normally shutdown but on one of the nodes this wasn't the cause. During upgrade of the ingress-controller metallb create the arpresponder on the wrong interface (L2 only) which cut the external connection to the ingress loadbalancer ip.

Will be great to get this improvment.

Nevertheless thanks for your awesome work on this project :clap:

**Comment by champtar** [comment]
Thinking about the route based solution, for the gratuitous case, we should only advertise on interfaces that can reach this ip. 
```
default via 10.11.12.1 dev eth0 proto static metric 100
10.11.12.0/24 dev eth0 proto kernel scope link src 10.11.12.13 metric 100
10.20.30.0/24 dev eth1 proto kernel scope link src 10.20.30.40 metric 100
```
10.11.12.200 should only be advertised on eth0
10.20.30.55 should only be advertised on eth1
1.2.3.4 should only be advertised on eth0
(we of course need to exclude kube-ipvs0 and maybe other interfaces like that)

This should be the default behavior, with an option to go back to the current behavior.
If 10.20.30.75 has a route like `1.2.3.4 dev eth1 scope link` and expect it to work, either they are fine without gratuitous ARP (normal ARP response should still work) or they can flip the switch "my network is weird just send gratuitous everywhere"

For responding to ARP we should do what Linux is doing by default

I'm deploying more and more K8S clusters in networks that I don't manage, and I'm seeing more and more dumb switch. I recently had the exact same problem as @HaveFun83.

**Comment by rdxmb** [comment]
@champtar wrote

> Thinking about the route based solution, for the gratuitous case, we should only advertise on interfaces that can reach this ip.

**Comment by rdxmb** [comment]
@RostyslavFridman  wrote
> Due to the current code limitations it can be done only as an option passed to the metallb executable itself

What is the syntax for that? Could you send me a link, please? Maybe this is a workaround for me until this is fixed.

**Comment by RostyslavFridman** [comment]
@rdxmb You will need to rebuild metallb with this patch:
```diff --git a/internal/layer2/announcer.go b/internal/layer2/announcer.go
index 1460490e..b2032972 100644
--- a/internal/layer2/announcer.go
+++ b/internal/layer2/announcer.go
@@ -13,7 +13,8 @@ import (
 
 // Announce is used to "announce" new IPs mapped to the node's MAC address.
 type Announce struct {
-	logger log.Logger
+	logger         log.Logger
+	bindInterfaces []string
 
 	sync.RWMutex
 	arps     map[int]*arpResponder
@@ -23,13 +24,14 @@ type Announce struct {
 }
 
 // New returns an initialized Announce.
-func New(l log.Logger) (*Announce, error) {
+func New(l log.Logger, ifaces ...string) (*Announce, error) {
 	ret := &Announce{
-		logger:   l,
-		arps:     map[int]*arpResponder{},
-		ndps:     map[int]*ndpResponder{},
-		ips:      map[string]net.IP{},
-		ipRefcnt: map[string]int{},
+		logger:         l,
+		bindInterfaces: ifaces,
+		arps:           map[int]*arpResponder{},
+		ndps:           map[int]*ndpResponder{},
+		ips:            map[string]net.IP{},
+		ipRefcnt:       map[string]int{},
 	}
 	go ret.interfaceScan()
 
@@ -77,6 +79,11 @@ func (a *Announce) updateInterfaces() {
 				continue
 			}
 		}
+
+		if len(a.bindInterfaces) > 0 && !isBindInterface(ifi.Name, a.bindInterfaces) {
+			continue
+		}
+
 		if ifi.Flags&net.FlagBroadcast != 0 {
 			keepARP[ifi.Index] = true
 		}
@@ -257,3 +264,12 @@ const (
 	dropReasonEthernetDestination
 	dropReasonAnnounceIP
 )
+
+func isBindInterface(interfaceName string, bindInterfaces []string) bool {
+	for _, b := range bindInterfaces {
+		if b == interfaceName {
+			return true
+		}
+	}
+	return false
+}
diff --git a/speaker/main.go b/speaker/main.go
index 63850910..2a4a6491 100644
--- a/speaker/main.go
+++ b/speaker/main.go
@@ -22,6 +22,7 @@ import (
 	"net"
 	"os"
 	"os/signal"
+	"strings"
 	"syscall"
 	"time"
 
@@ -75,6 +76,7 @@ func main() {
 		mlNamespace = flag.String("ml-namespace", os.Getenv("METALLB_ML_NAMESPACE"), "Namespace of the speakers (for MemberList / fast dead node detection)")
 		mlSecret    = flag.String("ml-secret-key", os.Getenv("METALLB_ML_SECRET_KEY"), "Secret key for MemberList (fast dead node detection)")
 		myNode      = flag.String("node-name", os.Getenv("METALLB_NODE_NAME"), "name of this Kubernetes node (spec.nodeName)")
+		ifaces      = flag.String("bind-interfaces", "", "bind interfaces; empty value starts announcers on all interfaces")
 		port        = flag.Int("port", 80, "HTTP listening port")
 	)
 	flag.Parse()
@@ -120,11 +122,17 @@ func main() {
 		}
 	}
 
+	bindInterfaces := make([]string, 0)
+	if *ifaces != "" {
+		bindInterfaces = strings.Split(*ifaces, ",")
+	}
+
 	// Setup all clients and speakers, config decides what is being done runtime.
 	ctrl, err := newController(controllerConfig{
-		MyNode: *myNode,
-		Logger: logger,
-		MList:  mlist,
+		MyNode:         *myNode,
+		Logger:         logger,
+		MList:          mlist,
+		BindInterfaces: bindInterfaces,
 	})
 	if err != nil {
 		logger.Log("op", "startup", "error", err, "msg", "failed to create MetalLB controller")
@@ -219,9 +227,10 @@ type controller struct {
 }
 
 type controllerConfig struct {
-	MyNode string
-	Logger gokitlog.Logger
-	MList  *memberlist.Memberlist
+	MyNode         string
+	Logger         gokitlog.Logger
+	MList          *memberlist.Memberlist
+	BindInterfaces []string
 
 	// For testing only, and will be removed in a future release.
 	// See: https://github.com/google/metallb/issues/152.
@@ -238,7 +247,7 @@ func newController(cfg controllerConfig) (*controller, error) {
 	}
 
 	if !cfg.DisableLayer2 {
-		a, err := layer2.New(cfg.Logger)
+		a, err := layer2.New(cfg.Logger, cfg.BindInterfaces...)
 		if err != nil {
 			return nil, fmt.Errorf("making layer2 announcer: %s", err)
 		}
```
Afterwards, you will be able to run speaker with additional flag `--bind-interfaces=<your_interfaces>`. Comma is a separator.

**Comment by rdxmb** [comment]
Oh, thanks @RostyslavFridman , but I am not going to compile this for myself. I am a system engineer using k8, not a go-developer...

**Comment by adampl** [comment]
@RostyslavFridman How would this work if different nodes have different interfaces?

**Comment by RostyslavFridman** [comment]
@adampl It doesn't. In our specific case we have uniformly named interfaces on different servers. Otherwise, you can pass a list of interfaces to advertise, but that might be unsuitable in your specifcic case. I agree with @danderson that this should be done through the configuration.

**Comment by adampl** [comment]
@RostyslavFridman Could you refactor your patch so that in addition to (or instead of) the CLI param, the interfaces would be taken from a node annotation? :D

**Comment by kfox1111** [comment]
In our case, we're running everything through openvswitch interfaces so our naming is usually consistent.

Node annotation would be cool though.

**Comment by h00pz** [comment]
> In the configuration, we have two conflicting objectives:
> 
> 1. Simple configurations should not require more than just a `interfaces: ["eno1"]` config entry.
> 2. Complex configurations need a format that's more painful to enter: a list of (interfaces, nodeSelector) pairs.
> 
> A solution to that is to have a global "interfaces" setting for simple configs, and a complex per-pool "interfaces" setting for complex configs. The final config is the union of the two, where the global config applies to all pools and all nodes.
> 
> A simple config would look like:
> 
> ```yaml
> layer2-config:
>   interfaces: ["eno1", "eno2"]
> address-pools:
>   - name: default
>     mode: layer2
>     addresses:
>       - 10.0.0.10 - 10.0.0.100
> ```
> 
> A complex config would look like:
> 
> ```yaml
> address-pools:
>   - name: default
>     protocol: layer2
>     addresses:
>       - 10.0.0.5 - 10.0.100.10
>     interfaces:
>       - interfaces: ["eno1", "vlan6"]
>         node-selectors:
>           - match-labels:
>               rack-name: foo
>           - match-labels:
>               rack-name: bar
>       - interfaces: ["eno2"]
>         node-selectors:
>           - match-labels:
>               rack-name: quux
> ```
> 
> In the complex config, the `interfaces` sections are additive: each node listens on the union of all interfaces that were selected by _any_ of the node selectors. An empty node selector means "all nodes". This makes it easy to express configs like "listen on eno1 everywhere, and also on vlan6 on specific machines."

wondering if you have implemented the interfaces option yet cuz I'm testing this out today and seeing "line 7: field interfaces not found in type config.addressPool","event":"configStale","msg":"config (re)load failed, config marked stale","ts":"2020-05-06T22:40:34.384195252Z"}"

**Comment by kfox1111** [comment]
Any movement on this?

**Comment by alchemistake** [comment]
Any updates?

**Comment by adampl** [comment]
@danderson What would you say to the code proposed by @RostyslavFridman? Do you have any plans about this feature?

**Comment by adampl** [comment]
Sorry Dave, I was unaware of this change.

@fedepaol Could you share your opinion, or forward this to the most adequate maintainer?

**Comment by fedepaol** [comment]
> Sorry Dave, I was unaware of this change.
> 
> @fedepaol Could you share your opinion, or forward this to the most adequate maintainer?

Let me go over all the discussion and will provide feedback. From a functional point of view, I have the gut feeling it could be added to https://github.com/metallb/metallb/pull/942 . It won't cover the security side of it thought.

**Comment by jmyoung** [comment]
This is a problem that I have due to the configuration of my machine - I have multiple interfaces, one pair of which is a LACP trunk going into OVS with multiple VLANs on it, and the other is an access port for the host.  MetalLB appears to respond to ARP on whatever interface it feels like, including the ones where incoming traffic can never actually get back to the k8s container.  Being able to tell MetalLB "only listen on _this_ interface" would be a lot, lot cleaner.  Having MetalLB respond to ARP on the "wrong interface" I believe causes me connectivity issues because of it suddenly causing a hairpin problem randomly between VMs that are running on the trunk and containers that are running on the host.

Note, I've probably got some of the terminology wonky, this stuff is pretty beyond me, but that's what my digging around for the past couple of days seems to have revealed.  I keep getting ARP responses back for my MetalLB addresses from MAC addresses that correspond to all sorts of other interfaces and not the one that the rest of k8s uses.

**Comment by kfox1111** [comment]
Getting metallb to speak only on the right interfaces I think is pretty important.

 @jmyoung, my workaround for now is to do something like this in the helm chart:
```yaml
  initContainers:
  - name: arp
    command:
    - /bin/sh
    - -ec
    - |
      ip link set dev ovsbr0 arp off;
```

And selectively turn off arp responses on things that metallb shouldn't be speaking on.

**Comment by qingwusunny** [comment]
Any plan about resolving this issue?

Maybe I can have a proposal in future week.

**Comment by fedepaol** [comment]
> cool, good to know! We need this feature urgent, can I know your plan more detailly? Maybe I can help if you need

Just to set the right expectations, I don't see this happening in short term.
We need somebody to work on a design proposal first, and to do the implementation later, and there's a lot of effort in landing https://github.com/metallb/metallb/blob/main/design/pool-configuration.md

**Comment by qingwusunny** [comment]
Alright, thanks for the information.
Can I provide the feature that specifies the interface list to announcers based on configmap first. And I can migrate it to CRD later.

**Comment by fedepaol** [comment]
> Alright, thanks for the information. Can I provide the feature that specifies the interface list to announcers based on configmap first. And I can migrate it to CRD later.

The configmap has been removed from the current development branch, so this is not an option. And also, we need to discuss a proper design first, so I suggest filing a design proposal if you are interested, considering the fact that I have limited bandwith to review it for the time being.

**Comment by qingwusunny** [comment]
OK
