### ISSUE TITLE
Store BGP passwords in secrets

### ISSUE THREAD

**Issue by junkiebev** [metallb/metallb#408]
I've deployed metallb in my cluster from version 0.8.4 and specified `configInline`.

If I am reading this correctly, it looks like if `configInline` is used, a config map is generated. I'm curious if it is possible to use secrets to specify `configInline.peers[0].password` values.

I'd presume that this would require some helm chart refactoring.

**Comment by danderson** [comment]
It's not currently possible. It's a reasonable feature request, although full disclosure it likely won't happen any time soon, as my free time to work on MetalLB is extremely limited.

**Comment by junkiebev** [comment]
Do you think it is just a chart modification or are you planning to handle it via environmental variables? Some other way? I might be able to take a stab at it if you can point me towards what you are thinking.

**Comment by danderson** [comment]
It requires code changes to MetalLB to read the right secret(s), and to recycle BGP connections when the secrets change. It's not _especially_ hard, but it's also not a trivial manifest change.

**Comment by Blorpy** [comment]
I realize this has been open for ages, but just throwing a +1 for this. 

It would be great if we could check the configmap into git, but doing so would currently require us to have the password in plaintext in there which is an issue since it's easily obtained. Since its also a very low bar to be able to source traffic from a k8s node IP, route hijacking and such security issues are a potential problem here. 

While we can apply prefix lists on the peer routers to limit what we accept/advertise to MetalLB, not having to store a secret in git in plaintext would be great!

**Comment by junkiebev** [comment]
This was closed
