### ISSUE TITLE
Remove the config reloading fail-static behavior

### ISSUE THREAD

**Issue by danderson** [metallb/metallb#462]
Right now, MetalLB tries hard to fail static if you delete its configuration, or provide an invalid/unsafe configuration. It does so by ignoring the new configuration (or the deletion of the configuration), and continues serving based on the last known config.

This is theoretically good, because it's a good guard against user error. The problem is k8s gives us no way of VERY LOUDLY telling the cluster operator that something is wrong. The best we can do is flip a Prometheus metric that says "hey we're running on a stale config." In practice, ~nobody does the Prometheus setup to detect this, so it just leads to mass confusion when MetalLB seems to not be working correctly (not allocating IPs to new services, announcing some services but not others...)

I originally thought that using a k8s admission controller would let us eagerly reject invalid configs. Unfortunately that's subject to a race condition where we might accept a config, but then a service changes state in a way that makes the config unsafe before we process the actual reloading. So, we can't make it behave correctly in all cases.

Given that k8s doesn't give us the lever we require, the only sensible thing to do is to remove the fail-static behavior, and always do exactly what the user tells us: if you push a config that makes some service IPs no longer valid, we'll change the service IPs. If you delete the configmap, MetalLB will un-announce all services and just stop doing anything.

It sucks because it means things are a bit less safe, but otoh it'll make MetalLB behave exactly like all other k8s services, in that what you told MetalLB to do is exactly what you'll get.

**Comment by CamelCaseNotation** [comment]
Is there a path forward for getting this done?

This current behavior causes problems when changing the addresses under an address pool in the configmap. Are you proposing the new behavior will cause any services which got an IP from the old pool to discard its current IP and get a new one?

**Comment by danderson** [comment]
In general, MetalLB already checks existing services with an assigned IP, and verifies that the IP makes sense given the configuration (i.e. that this service is "allowed" to have this IP). If the check fails, it deletes the assigned IP and goes through the assignment algorithm as if the service was brand new.

so yes, the new behavior would be that if you delete a pool from the config, all services with IPs from that pool will immediately lose their IP. If another IP can be allocated, that will happen.

**Comment by CamelCaseNotation** [comment]
> In general, MetalLB already checks existing services with an assigned IP, and verifies that the IP makes sense given the configuration (i.e. that this service is "allowed" to have this IP). If the check fails, it deletes the assigned IP and goes through the assignment algorithm as if the service was brand new.

This was not the behavior observed with the version of MetalLB we are running (v0.7.3).

We modified `addresses` field to a new range of addresses
```data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 131.153.252.110-131.153.252.125```

The previous range was `192.168.28.10 - 192.168.28.20`. We had a Service which had the IP `192.168.28.4` assigned from this old pool.

When we updated the ranges, the controller logs indicated the update to the configmap had failed. I believe this is the "stale config" you're referring to.

```{"caller":"main.go:114","configmap":"metallb-system/config","error":"new config not compatible with assigned IPs: service \"decco/k8sniff\" cannot own \"192.168.28.4\" under new config","msg":"applying new configuration failed","op":"setConfig","ts":"2019-08-09T21:40:20.150041105Z"}
{"caller":"k8s.go:338","configmap":"metallb-system/config","error":null,"event":"configStale","msg":"config (re)load failed, config marked stale","ts":"2019-08-09T21:40:20.150070566Z"}```

What we expected to happen is what you described in the above quote, but that was not the case. How do we get that behavior?

**Comment by danderson** [comment]
That's what this bug is about: the behavior I described doesn't happen, because MetalLB refuses to apply the new configuration. This bug is about removing that.

**Comment by CamelCaseNotation** [comment]
Okay excellent, I just wanted to make sure I understood correctly, thanks.

**Comment by adampl** [comment]
Well, the bug is still there in 0.8.3.

@danderson Are there any plans to fix it?

**Comment by jhughes2112** [comment]
Ping.  Ran into this trying to get MetalLB configured for the first time.  I have almost no idea what I'm doing, so configs change often.  All I can think to do is deliberately nuke the controller and speakers and hope it picks up the config.  I have no workloads on them, so this is safe.

I'd rather any error result in MetalLB sit idle, personally.  It'll be pretty clear that nothing is routing when the whole service goes down as a consequence of the action taken to change the IP range to something invalid.  Failing sooner related to the change being made helps with diagnostics.

**Comment by johananl** [comment]
I'm looking into this. If this takes time then at the very least we should put a big warning in the docs since new users keep getting bitten by this.

**Comment by jawabuu** [comment]
Hey @johananl just got bitten by this too when using k3s.  Two questions;
1. Given the current behaviour how would one force updtae the LoadBalancer IP?
2. A common use case for metallb would be HA cluster with say 3 masters and setting the default pool as below
```
- name: default
      protocol: layer2
      avoid-buggy-ips: true
      addresses:
      - 172.105.85.189/32
      - 139.162.162.133/32 
      - 139.162.178.46/32
      auto-assign: true 
```
How might I get metallb to switch to 2nd LoadBalncer IP if leader goes down?

**Comment by johananl** [comment]
@jawabuu regarding 1, on my testing deleting the MetalLB controller pod seems to work. The pod gets re-created and then MetalLB re-runs the reconciliation logic using the new config.
Until we remove the config reloading safety mechanism, MetalLB "remembers" the old IP and refuses to update it to a new IP to avoid breaking things.

Regarding 2, can you elaborate on the use case? What do you mean by "3 masters", "2nd LoadBalancer IP" and "leader"? Please describe the problem and the desired result clearly.

**Comment by jawabuu** [comment]
Hey @johananl Thank you for the workaround.

**Comment by jawabuu** [comment]
On point 2, I am spinning up a K3S Highly available cluster with 3 master nodes.
I am adding the external IPs of the three master nodes to my metalLB config.
```
- name: default
      protocol: layer2
      avoid-buggy-ips: true
      addresses:
      - 172.105.85.189/32
      - 139.162.162.133/32 
      - 139.162.178.46/32
      auto-assign: true 
```
On deploying traefik in the cluster, the traefik service of type LoadBalancer gets assigned the first IP.
So far so good.
To test HA, I bring down the first master node i.e. Leader. Pods from the former leader (including MetalLB ) are rescheduled to a new master. This is also OK.
I would like metalLB to assign a new IP of the current leader node to the LoadBalancer service. How can I achieve this?

**Comment by russellb** [comment]
> On point 2, I am spinning up a K3S Highly available cluster with 3 master nodes.
> I am adding the external IPs of the three master nodes to my metalLB config.
> 
> ```
> - name: default
>       protocol: layer2
>       avoid-buggy-ips: true
>       addresses:
>       - 172.105.85.189/32
>       - 139.162.162.133/32 
>       - 139.162.178.46/32
>       auto-assign: true 
> ```
> 
> On deploying traefik in the cluster, the traefik service of type LoadBalancer gets assigned the first IP.
> So far so good.
> To test HA, I bring down the first master node i.e. Leader. Pods from the former leader (including MetalLB ) are rescheduled to a new master. This is also OK.
> I would like metalLB to assign a new IP of the current leader node to the LoadBalancer service. How can I achieve this?

I think you've misunderstood how layer2 mode is supposed to work.  You should not be including IPs that are already assigned to Nodes.  These should be IP addresses dedicated to MetalLB's use and are *not* to be tied to a specific Node.  MetalLB will decide which Node the IP is currently assigned to.

**Comment by jawabuu** [comment]
Hey @russellb I do understand this. 
This is merely a workaround to `fake` a LoadBalancer on k3s or other setups where one cannot or does not wish to acquire a LoadBalancer.
MetalLB allows LoadBalancer Services to have the IP address populated and adds capability to use services such as ExternalDNS.

**Comment by russellb** [comment]
> I am adding the external IPs of the three master nodes to my metalLB config.

This specifically is a broken configuration, though.  Does it make sense why?  This is probably better for #metallb on kubernetes slack and not here, because this is getting a bit off topic from what this issue was about.

**Comment by champtar** [comment]
@jawabuu you want to use externalIPs, not MetalLB

**Comment by jawabuu** [comment]
@russellb This is well noted. This however is a common use case for faking LoadBalancer IP assignments.
@champtar How would this work?

**Comment by champtar** [comment]
@jawabuu slack please

**Comment by jawabuu** [comment]
@champtar  Thanks

**Comment by mlguerrero12** [comment]
`Given that k8s doesn't give us the lever we require, the only sensible thing to do is to remove the fail-static behavior, and always do exactly what the user tells us: if you push a config that makes some service IPs no longer valid, we'll change the service IPs. If you delete the configmap, MetalLB will un-announce all services and just stop doing anything.

It sucks because it means things are a bit less safe, but otoh it'll make MetalLB behave exactly like all other k8s services, in that what you told MetalLB to do is exactly what you'll get.`

I agree with this. Why should we give this kind of protection to the users if this lead us to inconsistencies? Metallb should do what it is instructed to do. Note that if the controller is restarted, the new config is taken and this leads to undesirable states (possible IP duplications).

This is also imposing some limitations in the design of the status for the IPAddressPool especially since there are 2 controllers interacting with the allocator struct.

@fedepaol , what is preventing us to take a decision on this?

**Comment by fedepaol** [comment]
> @fedepaol , what is preventing us to take a decision on this?

Nothing, I guess. We did not have users complaining hard enough, so this issue stayed in the background because it was probably not hitting enough users.

I agree MetalLB should do what it is instructed to, and maybe we could have a way to avoid the user deleting an ip that is being used or at least throw some alarms if a service changes its ip after a reconfiguration.
So, if this prevents moving forward, or it is a source of inconsistencies (which is, but not that hard) then we should reconsider and work it.

**Comment by funkycode** [comment]
Well I think the whole point of keep config is against the idea of controller. The whole point is to reconcile the current configuration and current state and if different - apply it.
In case validation is required it can be implemented in validations on applying changes to CRD and reject the apply itself, rather than controller to decide ignore it.
Moreover if logic is needed to be in controller itself there is possibility to implement it with adding extra status information and/or ConfigChangeRequest request.
For example instead of interacting with Pool Addresses CRD I would interact with CRD representing change request, where controller will monitor it and update it status to Success or Failure depending if it succeeded or failed to apply the change to Pool. This way I can programaticaly or manually "request" to make changes and see the result of change, while controller will handle of applying new config only if it is valid
