### ISSUE TITLE
The v0.8.3 Install link is using the v0.8.2 docker images

### ISSUE THREAD

**Issue by jenciso** [metallb/metallb#493]
When I used  the installation link 
https://raw.githubusercontent.com/google/metallb/v0.8.3/manifests/metallb.yaml
I saw into the spec container image the 0.8.2 version. It should be 0.8.3

**Comment by nodesocket** [comment]
Is this an issue? If so, can we get an updated version?

**Comment by jenciso** [comment]
It is not a big deal. I changed my ansible playbook to modify this yaml file and it works

**Comment by russellb** [comment]
We can't fix an old tag.  This would only be fixed by a new release and there have been releases since this bug was filed.  I also see that `tasks.py` which handles releases includes some commands to automatically update the version in the manifests, so hopefully it won't happen again.  That fix came in commit 9094482fa

I think we can close this
