### ISSUE TITLE
Potential solution for multiple eBGP sessions over same pair of K8S node and TOR

### ISSUE THREAD

**Issue by zy1ting** [metallb/metallb#495]
I'd like to propose a solution to have both calico eBGP and metalLB eBGP over the same K8S and TOR by using an eBGP session between the loopback interface on the K8S node and TOR for an eBGP multi-hop session.

1. bring up a loopback interface on K8S node and TOR

2. Calico peer eBGP session with TOR over directed connected physical link and let both K8S node and TOR to advertise all directly connected ip including the loopback's so there is reachability between two loopback interface.

3. metalLB peer an eBGP session between the loopback interface on K8S node and TOR. 

In this way, we keep the same BGP ASN on both eBGP sessions.

**Comment by Zyt612** [comment]
in fact, the ideal solution can be to add a feature allowing metalLB specify the local ip address/interface from which it will establish BGP sessions.

**Comment by arnaudgelly** [comment]
This is my current setup (seeing your post before would have saved me some time wondering if it was the right way) :


 ![K8S](https://user-images.githubusercontent.com/2733574/75915396-b54ad480-5e56-11ea-9b43-4d229e2969cd.png)


iBGP with Route Reflector on the 2 core routers (I don't see the advantage of eBGP).

MetalLB BGP sessions between loopbacks and Calico BGP sessions between LAN interfaces has you suggested.

Need a static route on the node toward core routers' loopbacks with the IP of the node's loopback IP has source :
`ip route <CORE-ROUTER-A-LOOPBACK-IP> via <GATEWAY> src <NODE-LOOPBACK-IP>`
`ip route <CORE-ROUTER-B-LOOPBACK-IP> via <GATEWAY> src <NODE-LOOPBACK-IP>`

Working well so far.

Adding the capability of specifying the source interface in the metalLB BGP configuration would simplify the node's configuration for sure.

ToR / Spine or VRF are good options but not adapted to my network topology.

Peering metalLB to calico inside the node is a nice idea but that imply some evolution on Calico's and metalLB BGP features (route-maps would be nice).

Looks like loopbacks is the best option for simple topology.

**Comment by ckoester2** [comment]
For what it's worth, I drafted up a quick code change to allow specifying a source interface to MetalLB: https://github.com/ckoester2/metallb/compare/main...ckoester2:issue-495

This needs a bit more testing before being ready for a PR, but in a nutshell, adds an optional `source-interface` configurable to the BGP peer configuration that may contain an interface name (not an IP address). Example:

```
    peers:
    - peer-address: 192.168.2.1
      peer-asn: 65123
      source-interface: lo_lb
      my-asn: 65125
```

This assumes that on each node in the cluster, an interface named `lo_lb` exists - in my test, I was creating this as a dummy interface, with the following file in (debian/ubuntu-based) `/etc/network/interfaces.d`:

```
auto lo_lb
iface lo_lb inet static
    address {{ metallb_loopback_ip }}
    netmask 255.255.255.255
    pre-up ip link add lo_lb type dummy
    post-down ip link del dev lo_lb
```

This still requires the peering router to have a route back to the Loopback interface - either by static route on the peering router, IGP, or piggybacked onto the other (eg. Calico)'s BGP session somehow.

**Comment by Zyt612** [comment]
> This is my current setup (seeing your post before would have saved me some time wondering if it was the right way) :
> 
> ![K8S](https://user-images.githubusercontent.com/2733574/75915396-b54ad480-5e56-11ea-9b43-4d229e2969cd.png)
> 
> iBGP with Route Reflector on the 2 core routers (I don't see the advantage of eBGP).
> 
> MetalLB BGP sessions between loopbacks and Calico BGP sessions between LAN interfaces has you suggested.
> 
> Need a static route on the node toward core routers' loopbacks with the IP of the node's loopback IP has source :
> `ip route <CORE-ROUTER-A-LOOPBACK-IP> via <GATEWAY> src <NODE-LOOPBACK-IP>`
> `ip route <CORE-ROUTER-B-LOOPBACK-IP> via <GATEWAY> src <NODE-LOOPBACK-IP>`
> 
> Working well so far.
> 
> Adding the capability of specifying the source interface in the metalLB BGP configuration would simplify the node's configuration for sure.
> 
> ToR / Spine or VRF are good options but not adapted to my network topology.
> 
> Peering metalLB to calico inside the node is a nice idea but that imply some evolution on Calico's and metalLB BGP features (route-maps would be nice).
> 
> Looks like loopbacks is the best option for simple topology.

@arnaudgelly , I am just curious what is your use case in which you need both MetalLB and Calico at the same time?

**Comment by arnaudgelly** [comment]
> > This is my current setup (seeing your post before would have saved me some time wondering if it was the right way) :
> > ![K8S](https://user-images.githubusercontent.com/2733574/75915396-b54ad480-5e56-11ea-9b43-4d229e2969cd.png)
> > iBGP with Route Reflector on the 2 core routers (I don't see the advantage of eBGP).
> > MetalLB BGP sessions between loopbacks and Calico BGP sessions between LAN interfaces has you suggested.
> > Need a static route on the node toward core routers' loopbacks with the IP of the node's loopback IP has source :
> > `ip route <CORE-ROUTER-A-LOOPBACK-IP> via <GATEWAY> src <NODE-LOOPBACK-IP>`
> > `ip route <CORE-ROUTER-B-LOOPBACK-IP> via <GATEWAY> src <NODE-LOOPBACK-IP>`
> > Working well so far.
> > Adding the capability of specifying the source interface in the metalLB BGP configuration would simplify the node's configuration for sure.
> > ToR / Spine or VRF are good options but not adapted to my network topology.
> > Peering metalLB to calico inside the node is a nice idea but that imply some evolution on Calico's and metalLB BGP features (route-maps would be nice).
> > Looks like loopbacks is the best option for simple topology.
> 
> @arnaudgelly , I am just curious what is your use case in which you need both MetalLB and Calico at the same time?

@Zyt612 , Sorry I don't understand what you mean. Isn't that the all point of this thread ?

**Comment by Zyt612** [comment]
@arnaudgelly I actually proposed the solution here to address the issue mentioned in the metallb website https://metallb.universe.tf/configuration/calico/. But I am trying to learn from anyone who has tried to use MLB and Calico at the same time in production and use eBGP to advertise routes. I thought you were doing that :)

**Comment by arnaudgelly** [comment]
@Zyt612 I wanted to deploy kubernetes across several datacenters without encapsulation or extended L2. I also wanted to use public /32 directly in kubernetes. Calico + MetalLB seems the best option for that. I still do get why eBGP instead of iBGP. What's the advantage ?

In your code suggestion you specify "source-interface" with an example of loopback configuration for Ubuntu. By specifying only the loopback IP address, wouldn't it be simpler considering the variety of underlying OS or setup ? What if I put a secondary IP on my eth0 interface ? What if it doesn't work on CentOS 8 ?

**Comment by ckoester2** [comment]
> In your code suggestion you specify "source-interface" with an example of loopback configuration for Ubuntu. By specifying only the loopback IP address, wouldn't it be simpler considering the variety of underlying OS or setup ? What if I put a secondary IP on my eth0 interface ? What if it doesn't work on CentOS 8 ?

Regarding this question, also see the comments in my draft PR #573 . Specifying the source *address* (as opposed to the source *interface name*) would indeed open up a broader variety of configuration options on the host, but would complicate the MetalLB configuration. Reason is that the source address is obviously unique to each node, so that would necessitate some sort of "per-node" configuration data structure on the MetalLB configmap - and the onus on the operator to synchronize this with the node, ie. making sure that the same address is specified in the configmap as exists on the host.

So from that perspective, when drafting up a PR, having only a single interface name per BGP peer, seemed to reduce the resulting complexity of the configmap - but of course, assumes that an interface with that name is created on each host. This *could* be a Loopback (or rather a "dummy" interface in Linux terms, as Linux tends to use the "loopback" interface type only for 127..0.0/8), or any other interface that exists on the node other than the interface used by Calico.

**Comment by arnaudgelly** [comment]
Thank you @ckoester2 for all your information. The simplification by using only interface name make sens.

It's not clear for me all the implications using a dummy interface instead of an alias on a loopback.

At least the 'ip addr show' command doesn't filter alias interfaces and answer all the addresses contrary to a dedicated dummy interface.
