### ISSUE TITLE
Does not send responses on proper interface

### ISSUE THREAD

**Issue by skandragon** [metallb/metallb#533]
v0.8.3

I'm running Metallb on a small raspberry pi cluster.  I have two interfaces:

eth0: 10.45.0.0/16
vlan17: 10.46.0.0/16

I have specified 10.46.200.0 to 10.46.240.255 as possible external addresses, and the first service is assigned 10.46.200.0.

I can reach this address from the router (pfsense) and all is well.   The router sends on vlan17, and responses go back on vlan17 due to routing.

However, when I attempt to reach the service from a different address which would normally be reached via eth0 (say, 10.42.0.1), the responses go out eth0.  These are rejected by the router as being spoofed.

While I understand the desire to not have any config to use only certain interfaces, I believe it is a requirement in this case, or I have to add some routing table magic to say "if the source is 10.46.0.0/16, and the destination isn't 10.46.0.0/16, send to the router at 10.46.255.254/32"

Is there a work-around other than mucking with the routing table somehow?

**Comment by champtar** [comment]
Hi @skandragon 
In L2 mode, metalLB does the following:
1) pick an IP from the IP pool in the config and attributes it to the k8s LoadBalancer (patch the status field)
2) answer ARP requests
Everything else is handled by k8s kube-proxy.

The problem you describe is not even k8s related for me, say node A has IPs 10.45.0.A and 10.46.0.A, what happens when you try to reach 10.46.0.A from 10.42.0.1 ?

**Comment by skandragon** [comment]
You're right, this is just a routing issue.  I can either try hard to fix this, or just allow ingress from off-net addresses on the other interface.  Guess which one I'll go for in a small home experimental lab?
