### ISSUE TITLE
external access unavailable after vmotion VMware

### ISSUE THREAD

**Issue by marcelogimenes** [metallb/metallb#571]
I'm running my Kubernetes cluster over on-premise virtual machines (VMWare), with MetalLB in layer2 mode. When we performed a VMotion operation in one of the workers, we could no longer access our cluster applications from outside (through ingress, haproxy, in our case). When checking ARP table at the network switch, the IP address assigned by MetalLB controller did not have any corresponding MAC address. To solve this problem we had to restart the haproxy ingress-controller POD.  Has someone already faced this problem ? 

metallb: 0.7.3
calico 3.7.3 
kubernetes: 1.15.3
kube-proxy mode iptables
Kubernetes 1.15.3

**Comment by rata** [comment]
Hi!

Can you please try with a newer MetalLB version (0.9.3) and if it still happens, try to describe how to reproduce?

If a license is needed for VMware, it would be great if you happen to find a way to reproduce it without it (as it's not easy for me to get one currently).

**Comment by russellb** [comment]
Just to make sure I understand the scenario, I take it you are using metallb to expose your ingress controller pod?  What happens when you restart your ingress controller pod, does the load balancer service move and the IP get announced from a new host in the cluster?

Your workaround makes it sound like MetalLB can fix this by sending out another round of gratuitous ARPs, but I'm not sure how it should know that this needs to happen.

I'm curious, what kind of network are you using for the VMs?  I do wonder if this would be avoided if the cluster was using NSX-T, so the network itself was aware of the move of that specific device on the network.  I'm definitely not a vmware expert, though.

**Comment by jetersen** [comment]
We are running MetalLB v0.9.3 and are seeing this issue when using layer2.
Initially the ingress was running as deployment with 3 replica. 
Tried to change to Daemonset so all our workers have a ingress, this improved the situation slightly but still happens.

Would have to talk to our vSphere admins on how we do networking for our VMs.
Though I wonder if BGP mode would alleviate the problem.

**Comment by russellb** [comment]
I suspect BGP mode would work better if it works in this environment, yes.

The main open question is how metallb should know it should send out gratuitous ARPs.  Otherwise I don't know what could be done other than document this as a known issue.
