### ISSUE TITLE
Use distroless static images

### ISSUE THREAD

**Issue by alex1989hu** [metallb/metallb#676]
It is a common practise to use `SRATCH` or `distroless/static` images for Go executables, thus no need to use `alpine` image.

I did not find any use case where an existing shell is needed, but please add your comment here.

Either `SRATCH` or `distroless/static` image does not contain shell which reduces attack surface and size, too.

Image size changes:
| controller                | Size       |
|------------------- | -------- |
| `alpine`                   | 74.8MB |
| `distroless/static`  | 36.4MB |

| speaker                   | Size       |
|------------------- | -------- |
| `alpine`                   | 83.6MB |
| `distroless/static`  | 40.9MB |

**Comment by russellb** [comment]
I like having a shell for debugging purposes.

I guess this will come down to what we feel is the best setup for what images are distributed by default.  Options could include:

* This PR to change the default and only image we publish to be a static image
* Just add a sample Dockerfile for a static image (that we do test builds of in CI)
* publish both image types ...

I think I'd lean toward leaving the existing default, and adding another sample Dockerfile would be fine too.

I honestly expect many people to build their own images in their own pipelines, anyway.

**Comment by rata** [comment]
@russellb you mean a shell for debugging purposes on a local env or in prod?

For production I was thinking distroless was more useful with the ephemeral containers k8s feature (not sure if it's alpha or beta). With that, you can basically add a container on the fly to the pod, and do whatever you like (like `ngrep`, etc.). And as the metalLB image is just a binary, there isn't much in the filesystem to inspect. And ephemeral container will just do the trick, I think.

I agree is something to take into account, definitely. I would not expect people to compile MetalLB on their own, though. So, I think is important to have a fairly useful default for most users.

@alex1989hu What do you think of the options @russellb proposed? Any preference?

**Comment by russellb** [comment]
For my own production use cases, I'll have my own custom built and signed images.  The way this impacts me mostly personally is for development.  I haven't tried ephemeral containers, but it sounds like it would support my use case.  I'm just used to opening up shells in the existing containers to poke around when needed.  :-)

I really don't feel too strongly about this one and definitely have no interest in blocking it either way.

**Comment by alex1989hu** [comment]
Hello @russellb @rata: i do not think it is worth to produce a `debug` image with extra shell. Additionally, it will multiply all the supported arch (e.g. `arm64`) - to be honest, I did not check what are the current supported platforms. I also like to enter into container's, I see your point, @russellb.

I must say, at most of the cases I do not enter, but if it is the case, then something is wrong ... usually **(always)** the next step is to replace the container with my self baked binary (e.g. add some extra logs) and figure out what is going on.

I think the most common use case for end-users is just to deploy `metallb` and "forget" it (works good). This use case profits the most with the `distroless/static` image by the already mentioned image size reduction (lower disk pressure, less network usage, faster image start) and minimized attak surface.

**Comment by johananl** [comment]
Thank you @alex1989hu for your contribution!

Sharing my thoughts here:

- I like the idea of using minimal container images as much as possible.
- I agree that in many cases you don't need to get shell access into a container, however in the few cases where it *is* necessary it's really annoying not to have it.
- While I'm sure *some* people would opt for building their own images, I'm certain lots of users just use the official manifests and images as-is. Also, I believe the need for building custom images becomes less relevant if the images we ship are thin without lots of place for vulnerabilities.
- I'm reluctant to shipping images without a shell until ephemeral containers are GA and mainstream (or until we have an alternative way for debugging). Right now it seems one needs to tweak the cluster in order to use ephemeral containers. I couldn't get them to work using the cluster created by `inv dev-env` for example (which is `v1.17.0`), and I'm sure many people can't even tweak feature gates since they're using managed k8s services.
- IMO we should prefer shipping **one** set of images to avoid confusing users and to make maintenance easier.

Combining all of the above, I suggest we keep the Alpine-based images for now (which means closing #677) and re-evaluate when ephemeral containers become more mainstream. Again @alex1989hu, I appreciate the initiative but I'm not convinced it makes sense to give up the shell right now.

**Comment by russellb** [comment]
Thanks, @johananl, I agree with that take

**Comment by champtar** [comment]
Ephemeral containers are alpha since 1.16, so nobody has them
https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/
