### ISSUE TITLE
Feature request: non-revertive L2 vip ownership

### ISSUE THREAD

**Issue by orenye** [metallb/metallb#704]
A feature request: add a configuration to enable a non-revertive vip ownership behavior for L2 mode.

This behavior is required to avoid a double hit in cases that involve long lived tcp sessions, as described here:
When the vip owner node goes down, the vip ownership jumps to a backup node, all the long lived tcp sessions are disconnected and the clients are establishing new sessions with the backup node.
Then when the failed node comes back to life, it takes back the vip ownership and all the tcp sessions are disconnected once again.
The requested change in behavior: When the failed node comes back to life, it won't take back the vip ownership and by that won't harm the existing tcp connections.

**Comment by johananl** [comment]
This sounds similar to the **VRRP preempt** option. It does make sense to me to minimize switching activity as much as possible, especially when the user doesn't care which node is the active one. I would even consider making this the default behavior and possibly allowing users to override the default using a config knob.

Here is what we're doing at the moment:

https://github.com/metallb/metallb/blob/44f7ae9edf6ed2bd724e7b4b14a21596b4525bb8/speaker/layer2_controller.go#L78-L97

Since we sort the slice of nodes by name (plus service name), assuming node and service names don't change we will always get the same node at index `0` when all nodes are healthy.

https://github.com/metallb/metallb/issues/621 is likely related.

The main thing I'd like to figure out:

Does it make sense to change the **default** behavior in order to minimize switching activity as much as possible?

If the answer is "no", we would have to introduce a config change to allow users to control things. If the answer is "yes", we could *optionally* add a new config option to allow users to toggle this behavior off (i.e. in case they *want* to switch activity back to the "original" node upon convergence).

**Comment by liuyuan10** [comment]
To add more context, this has been discussed a little bit in #561. +1 for this feature request, but it will make current implementation more complex.

**Comment by pyDream** [comment]
> This sounds similar to the **VRRP preempt** option. It does make sense to me to minimize switching activity as much as possible, especially when the user doesn't care which node is the active one. I would even consider making this the default behavior and possibly allowing users to override the default using a config knob.
> 
> Here is what we're doing at the moment:
> 
> https://github.com/metallb/metallb/blob/44f7ae9edf6ed2bd724e7b4b14a21596b4525bb8/speaker/layer2_controller.go#L78-L97
> 
> Since we sort the slice of nodes by name (plus service name), assuming node and service names don't change we will always get the same node at index `0` when all nodes are healthy.
> 
> #621 is likely related.
> 
> The main thing I'd like to figure out:
> 
> Does it make sense to change the **default** behavior in order to minimize switching activity as much as possible?
> 
> If the answer is "no", we would have to introduce a config change to allow users to control things. If the answer is "yes", we could _optionally_ add a new config option to allow users to toggle this behavior off (i.e. in case they _want_ to switch activity back to the "original" node upon convergence).

Hello, I would like to know what happened with this feature in the end, has it been implemented?

**Comment by johananl** [comment]
Hi @pyDream. I am no longer a MetalLB maintainer, but looking at the above it seems like the issue has been closed by a triage bot so my guess is -- no, this hasn't been implemented.

**Comment by fedepaol** [comment]
I can confirm that, it wasn't implemented (thanks @johananl for replying!)
