### ISSUE TITLE
Add official API for following L2 node announcements

### ISSUE THREAD

**Issue by invidian** [metallb/metallb#761]
As far as I am aware, if one wants to follow node announcements right now in a programmatic way, the only way to do this right now is by watching `Event` resources which are emitted for Service objects with `type: LoadBalancer`. From Event message, node name can be extracted.

Cloud providers like Hetzner Cloud offer Floating IPs, which can be assigned to nodes, which can be used as a cheap alternative to Cloud Load Balancers. To automate assignments of floating IP to servers, one should have a way to subscribe to node announcements and then do corresponding calls to Hetzner Cloud API to reflect MetalLB announcements.

It would be great to have some sort of well-defined resource (CRD maybe?), which can be watched and which would have an information which cluster node currently announces the traffic.

The resource could also be used for other purposes like https://github.com/metallb/metallb/issues/621, to announcing node can be manually selected?

**Comment by johananl** [comment]
The idea behind layer 2 mode is that you have layer 2 connectivity between the nodes so that you can rely on ARP to switch "activity" between speakers without having to change anything at the upstream switch/router. Sounds like Hetzner is doing something strange if you have to **configure** which node has an IP at the API level. Maybe they don't provide "real" layer 2 connectivity and the API change is required to make their SDN do the magic.

That said, I see no harm in being able to query the status of the currently-active node for a service. https://github.com/metallb/metallb/pull/593 introduces the notion of a "status endpoint" that is currently implemented for BGP only. We could probably expose the relevant information as JSON in the status endpoint for layer 2, but keep in mind that this endpoint is not a well-defined API and is introduced in that PR mainly to allow humans figure out the in-memory BGP configuration of a given speaker.

CRDs are discussed in https://github.com/metallb/metallb/issues/196. We aren't actively working on moving to CRDs at the moment so I wouldn't count on that being available in the short run.

**Comment by fedepaol** [comment]
Closing as being implemented in https://github.com/metallb/metallb/issues/2158
